const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
const A={role:'adult'},START='2026-09-28';
function base(){const s=C.seed(START);s.weeks=[];s.absences=[];s.presencePlans=[];s.presenceOverrides=[];s.finance.accounts=[];s.finance.dues=[];s.finance.ledger=[];s.templates=[{id:'daily',title:'Hacer la cama',points:10,memberIds:['ana'],days:[0,1,2,3,4,5,6],active:true,frequency:'daily'}];C.generateWeek(s,START);C.enableHomaRules(s,START);return s;}
function presence(s,cycle){return C.configurePresence(s,{memberId:'ana',anchor:START,from:START,until:'',cycle,type:'custom',title:'Convivencia'},A,START);}
function allDone(s){const w=s.weeks.find(w=>w.start===START);for(const t of w.tasks.filter(t=>t.status!=='excused'))C.setStatus(w,t.id,'done',A);return C.stats(w,'ana');}
function account(s,policy='fixed'){C.configureAllowance(s,{memberId:'ana',weeklyCents:500,enabled:true,payDay:6,savePercent:20,policy,tiers:policy==='tiers'?[{min:0,max:null,cents:500}]:[]},A,START);}
test('partial residence retains the full 70-point target',()=>{const s=base();presence(s,[true,true,false,false,true,false,false]);const st=allDone(s);assert.equal(st.target,70);assert.equal(st.points,70);assert.equal(st.presentDays,3);assert.equal(st.normalised,true);});
test('seven days and two days can both earn exactly 100',()=>{for(const cycle of [Array(7).fill(true),[true,true,false,false,false,false,false]]){const s=base();presence(s,cycle);C.configureHomaTarget(s,'ana',100,A,START);assert.equal(allDone(s).points,100);}});
test('normalised integer weights add to target with deterministic remainder',()=>{const s=base();presence(s,[true,true,true,false,false,false,false]);C.configureHomaTarget(s,'ana',100,A,START);const w=s.weeks[0],t=w.tasks.filter(t=>t.status!=='excused'),values=t.map(x=>C.taskPoints(w,x));assert.deepEqual([...values].sort(),[33,33,34]);assert.equal(values.reduce((a,b)=>a+b,0),100);});
test('base weights are not rewritten',()=>{const s=base();presence(s,[true,false,false,false,false,false,false]);assert.ok(s.weeks[0].tasks.every(t=>t.points===10));assert.equal(C.taskPoints(s.weeks[0],s.weeks[0].tasks[0]),70);});
test('missed/done correction returns accurate compensated delta',()=>{const s=base();presence(s,[true,true,false,false,false,false,false]);const w=s.weeks[0],t=w.tasks[0];assert.equal(C.setStatus(w,t.id,'missed',A),-35);assert.equal(C.setStatus(w,t.id,'done',A),70);assert.equal(C.stats(w,'ana').points,35);assert.equal(C.setStatus(w,t.id,'done',A),0);});
test('manual adjustments and recovery are not multiplied',()=>{const s=base();presence(s,[true,false,false,false,false,false,false]);const w=s.weeks[0];C.addRecovery(w,{memberId:'ana',title:'Extra',points:5,date:START});const t=w.tasks.at(-1);C.setStatus(w,t.id,'done',A);assert.equal(C.stats(w,'ana').points,5);assert.equal(C.stats(w,'ana').target,70);});
test('whole absent week is paused not reward unlocked',()=>{const s=base();presence(s,[false]);const st=C.stats(s.weeks[0],'ana');assert.equal(st.paused,true);assert.equal(st.points,0);assert.equal(st.target,0);assert.equal(C.rewardState(s.weeks[0],{memberId:'ana',mode:'weekly',active:true}).unlocked,false);});
test('full week holiday suppresses a fixed allowance',()=>{const s=base();presence(s,[false]);account(s);C.syncAllowanceDues(s,'2026-10-04');const d=s.finance.dues.find(d=>d.memberId==='ana');assert.equal(d.status,'skipped');assert.equal(d.cents,0);assert.equal(d.homaAbsenceSkip,true);assert.throws(()=>C.payAllowance(s,d.id,A,'2026-10-04'),/fuera/);assert.equal(s.finance.ledger.length,0);});
test('full absent week suppresses goal and tier allowances including zero-point tier',()=>{for(const policy of ['goal','tiers']){const s=base();presence(s,[false]);account(s,policy);C.syncAllowanceDues(s,'2026-10-11');assert.ok(s.finance.dues.length>0);assert.ok(s.finance.dues.every(d=>d.status==='skipped'&&d.cents===0));}});
test('a partial week keeps full fixed allowance',()=>{const s=base();presence(s,[true,false,false,false,false,false,false]);account(s);C.syncAllowanceDues(s,'2026-10-04');const d=s.finance.dues[0];C.payAllowance(s,d.id,A,'2026-10-04');assert.equal(d.status,'paid');assert.equal(d.cents,500);});
test('paid entries never disappear when presence is changed',()=>{const s=base();account(s);C.syncAllowanceDues(s,'2026-10-04');C.payAllowance(s,s.finance.dues[0].id,A,'2026-10-04');const ledger=JSON.stringify(s.finance.ledger);presence(s,[false]);C.syncAllowanceDues(s,'2026-10-04');assert.equal(s.finance.dues[0].status,'paid');assert.equal(JSON.stringify(s.finance.ledger),ledger);});
test('closed-week target and presence are frozen after new config',()=>{const s=base();presence(s,[true,false,false,false,false,false,false]);allDone(s);C.closeWeek(s.weeks[0]);const before=JSON.stringify(s.weeks[0]);C.configureHomaTarget(s,'ana',120,A,'2026-10-05');assert.equal(JSON.stringify(s.weeks[0]),before);assert.equal(C.stats(s.weeks[0],'ana').points,70);});
test('legacy historical weeks are not retroactively compensated',()=>{const s=base();delete s.settings.homaRules;delete s.weeks[0].homa;C.closeWeek(s.weeks[0]);const before=JSON.stringify(s.weeks[0]);C.enableHomaRules(s,'2026-10-05');assert.equal(JSON.stringify(s.weeks[0]),before);});
test('open-week holiday correction restores pending allowance',()=>{const s=base();const p=presence(s,[false]);account(s);C.syncAllowanceDues(s,'2026-10-04');C.cancelPresence(s,p.id,A);C.syncAllowanceDues(s,'2026-10-04');assert.equal(s.finance.dues[0].status,'pending');assert.equal(s.finance.dues[0].cents,500);});
test('no holiday debt is generated for completely unvisited weeks',()=>{const s=base();presence(s,[false]);account(s);C.syncAllowanceDues(s,'2026-11-01');assert.ok(s.finance.dues.length>=5);assert.ok(s.finance.dues.every(d=>d.status==='skipped'));});
test('future weeks use unchanged target when new tasks are added',()=>{const s=base();presence(s,[true,false]);s.templates[0].points=20;C.generateWeek(s,'2026-10-05');assert.equal(C.stats(s.weeks.at(-1),'ana').target,70);});
test('normalisation survives JSON backup validation',()=>{const s=base();presence(s,[true,true,false,false,true,false,false]);allDone(s);const restored=C.validateState(JSON.parse(JSON.stringify(s)));assert.equal(C.stats(restored.weeks[0],'ana').points,70);});
test('invalid normalisation state is rejected',()=>{const s=base();presence(s,[true,false]);s.weeks[0].homa.members.ana.target=-1;assert.throws(()=>C.validateState(s));});
test('child cannot configure the stable target',()=>{const s=base();assert.throws(()=>C.configureHomaTarget(s,'ana',100,{role:'member',memberId:'ana'},START));});
test('no assignments does not create free weekly reward',()=>{const s=base();presence(s,[true,false]);C.configureHomaTarget(s,'ana',100,A,START);s.weeks[0].tasks=[];C.applyAbsences(s);const st=C.stats(s.weeks[0],'ana');assert.equal(st.target,100);assert.equal(st.points,0);});

test('routine excludes automatically excused away-day steps',()=>{const s=base();presence(s,[false]);const r={memberId:'ana',templateIds:['daily']};assert.equal(C.routineTasks(s,r,START).length,0);});
