const test=require('node:test'),assert=require('node:assert/strict'),{apply,execute}=require('../server/operations.cjs'),C=require('../core.js');
const adult={householdId:'home1',role:'adult',userId:'u1'},child={householdId:'home1',role:'child',memberId:'ana',deviceId:'d1'};
const state=()=>C.seed('2026-10-03');const cmd=(type,payload,id='operation_one')=>({householdId:'home1',type,payload,id});
test('server refuses cross-household principal',()=>assert.throws(()=>apply(state(),cmd('shopping.state',{}),{...adult,householdId:'other'}),/FORBIDDEN/));
test('server ignores a forged adult role inside payload',()=>{const s=state(),before=C.balances(s,'ana').total;assert.throws(()=>apply(s,cmd('money.deposit',{memberId:'ana',cents:100,note:'X',role:'adult'}),child),/FORBIDDEN/);assert.equal(C.balances(s,'ana').total,before);});
test('server time prevents future task despite forged browser clock',()=>{const s=state(),w=s.weeks.find(w=>w.start==='2026-09-28'),t=w.tasks.find(t=>t.memberId==='ana'&&t.date==='2026-10-04');t.status='pending';assert.throws(()=>apply(s,cmd('task.status',{weekId:w.id,taskId:t.id,status:'done',today:'2099-01-01'}),child,new Date('2026-10-03T12:00:00Z')));});
test('server allows authorized adult deposit with server timestamp',()=>{const s=state(),before=C.balances(s,'ana').total,n=apply(s,cmd('money.deposit',{memberId:'ana',cents:100,note:'Regalo'}),adult,new Date('2026-10-03T12:00:00Z'));assert.equal(C.balances(n,'ana').total,before+100);assert.equal(n.updatedAt,'2026-10-03T12:00:00.000Z');assert.equal(C.balances(s,'ana').total,before);});
test('server will not execute unknown arbitrary state patches',()=>assert.throws(()=>apply(state(),cmd('replaceState',{finance:{}}),adult),/UNSUPPORTED_COMMAND/));
test('server child cannot transfer another child balance',()=>assert.throws(()=>apply(state(),cmd('money.transfer',{memberId:'leo',from:'available',to:'savings',cents:1}),child)));
test('server revoked device denied before operation',()=>assert.throws(()=>apply(state(),cmd('shopping.state',{}),{...child,revoked:true}),/FORBIDDEN/));
function repo(){let row={state:state(),revision:0},receipts=new Map(),tail=Promise.resolve();return {transaction(id,fn){const op=tail.then(()=>fn({read:async()=>structuredClone(row),receipt:async id=>receipts.get(id),commit:async(state,revision,id,result)=>{row={state,revision};receipts.set(id,result);}}));tail=op.catch(()=>{});return op;},get(){return row;}};}
test('server repeated operation id returns receipt, one money movement',async()=>{const r=repo(),c=cmd('money.deposit',{memberId:'ana',cents:100,note:'Gift'}),before=C.balances(r.get().state,'ana').total;const a=await execute(r,c,adult),b=await execute(r,c,adult);assert.equal(a.replayed,false);assert.equal(b.replayed,true);assert.equal(C.balances(r.get().state,'ana').total,before+100);});
test('server concurrent operations serialize without dropping a deposit',async()=>{const r=repo(),before=C.balances(r.get().state,'ana').total;await Promise.all([execute(r,cmd('money.deposit',{memberId:'ana',cents:100,note:'A'},'operation_a'),adult),execute(r,cmd('money.deposit',{memberId:'ana',cents:200,note:'B'},'operation_b'),adult)]);assert.equal(C.balances(r.get().state,'ana').total,before+300);assert.equal(r.get().revision,2);});
test('server stale expected revision rejects rather than overwrites',async()=>{const r=repo();await execute(r,cmd('money.deposit',{memberId:'ana',cents:100,note:'A'}),adult);await assert.rejects(()=>execute(r,{...cmd('money.deposit',{memberId:'ana',cents:100,note:'B'},'operation_b'),expectedRevision:0},adult),/VERSION_CONFLICT/);});

test('server idempotency key cannot be reused with another amount',async()=>{const r=repo();await execute(r,cmd('money.deposit',{memberId:'ana',cents:100,note:'A'}),adult);await assert.rejects(()=>execute(r,cmd('money.deposit',{memberId:'ana',cents:200,note:'A'}),adult),/IDEMPOTENCY_CONFLICT/);assert.equal(r.get().revision,1);});
test('server receipt cannot be replayed by another principal',async()=>{const r=repo(),c=cmd('money.deposit',{memberId:'ana',cents:100,note:'A'});await execute(r,c,adult);await assert.rejects(()=>execute(r,c,child),/FORBIDDEN/);});
test('server null payload is explicitly rejected',()=>assert.throws(()=>apply(state(),cmd('shopping.state',null),adult),/INVALID_COMMAND/));
