const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js'),V21=require('../core-v21.js');
const adult={role:'adult'},child={role:'member',memberId:'ana'},today='2026-10-03';
function fresh(){const s=C.seed(today);s.finance.accounts=[];s.finance.dues=[];s.finance.ledger=[];s.finance.savingsPlans=[];return s;}
function deposit(s,pocket,cents,date='2026-09-27',ref=null){const e=C.postMoney(s,'ana',{[pocket]:cents},'deposit','Test',ref,adult);e.at=date+'T12:00:00Z';return e;}
function plan(s,rate=10,period='month',date='2026-09-28'){return C.configureSavings(s,{memberId:'ana',rate,period,enabled:true},adult,date);}
const tiers=[{min:0,max:19,cents:0},{min:20,max:39,cents:200},{min:40,max:null,cents:500}];
function configure(s,extra={}){C.configureAllowance(s,{memberId:'ana',weeklyCents:0,payDay:0,savePercent:50,enabled:true,policy:'tiers',tiers,...extra},adult,'2026-09-28');}
function pts(s,n){const w=s.weeks.find(w=>w.start==='2026-09-28');w.tasks.filter(t=>t.memberId==='ana').forEach(t=>t.status='pending');w.adjustments=w.adjustments.filter(a=>a.memberId!=='ana');w.adjustments.push({id:'test-points',memberId:'ana',points:n,reason:'Test'});return w;}
function presence(s,type='alternate',extra={}){return C.configurePresence(s,{memberId:'ana',type,title:'Test',anchor:'2026-09-28',from:'2026-09-28',cycle:extra.cycle||C.presencePattern(type),...extra},adult,today);}
test('v2.1 migration retains all money and creates no yield',()=>{const s=V21.seed(today),before=JSON.stringify(s.finance.ledger);C.validateState(s);assert.equal(s.schemaVersion,3);assert.equal(JSON.stringify(s.finance.ledger),before);assert.equal(s.finance.savingsPlans.length,0);});
test('unknown schema rejected, null safely rejected',()=>{assert.throws(()=>C.validateState(null));const s=fresh();s.schemaVersion=99;assert.throws(()=>C.validateState(s));});
test('compound interest approximates one full effective period to within one cent',()=>{const s=fresh();deposit(s,'savings',10000);plan(s);C.accrueInterest(s,'2026-10-28');assert.ok(Math.abs(C.balances(s,'ana').savings-11000)<=1);C.validateState(s);});
test('interest never credits available spending pocket',()=>{const s=fresh();deposit(s,'available',90000);plan(s);C.accrueInterest(s,'2026-10-28');assert.equal(C.balances(s,'ana').total,90000);});
test('goal savings earn yield and credits go to main savings',()=>{const s=fresh(),g=s.finance.goals.find(x=>x.memberId==='ana');deposit(s,'goal:'+g.id,10000);plan(s);C.accrueInterest(s,'2026-10-28');const b=C.balances(s,'ana');assert.equal(b['goal:'+g.id],10000);assert.ok(b.savings>=999);});
test('daily accrual is idempotent with unique references',()=>{const s=fresh();deposit(s,'savings',10000);plan(s);C.accrueInterest(s,'2026-10-28');const before=JSON.stringify(s.finance);assert.equal(C.accrueInterest(s,'2026-10-28'),false);assert.equal(JSON.stringify(s.finance),before);});
test('new deposits start the following day, not retroactively',()=>{const s=fresh();deposit(s,'savings',10000,'2026-10-02');plan(s);C.accrueInterest(s,'2026-10-03');assert.equal(C.balances(s,'ana').savings,10000);C.accrueInterest(s,'2026-10-04');assert.ok(C.balances(s,'ana').savings>10000);});
test('withdrawals reduce same-day interest base',()=>{const s=fresh();deposit(s,'savings',10000);const e=C.transferMoney(s,'ana','savings','available',5000,child);e.at='2026-09-28T15:00:00Z';assert.equal(C.dailySavingsBase(s,'ana','2026-09-28'),5000);});
test('goal-to-savings transfers do not duplicate interest base',()=>{const s=fresh(),g=s.finance.goals.find(x=>x.memberId==='ana');deposit(s,'goal:'+g.id,10000);const e=C.transferMoney(s,'ana','goal:'+g.id,'savings',5000,child);e.at='2026-09-28T15:00:00Z';assert.equal(C.dailySavingsBase(s,'ana','2026-09-28'),10000);});
test('fractions below a cent survive between calculations',()=>{const s=fresh();deposit(s,'savings',100);const p=plan(s,10,'year');C.accrueInterest(s,'2026-09-30');assert.ok(p.carryMicro>0);C.accrueInterest(s,'2026-11-20');assert.ok(C.balances(s,'ana').savings>=101);});
test('zero percent never manufactures money',()=>{const s=fresh();deposit(s,'savings',10000);plan(s,0);C.accrueInterest(s,'2026-10-28');assert.equal(C.balances(s,'ana').savings,10000);});
test('rate changes settle old periods and never rewrite entries',()=>{const s=fresh();deposit(s,'savings',10000);plan(s);C.accrueInterest(s,'2026-10-03');const entries=JSON.stringify(s.finance.ledger);C.configureSavings(s,{memberId:'ana',enabled:true,rate:20,period:'month'},adult,today);assert.equal(JSON.stringify(s.finance.ledger),entries);C.accrueInterest(s,'2026-10-04');assert.equal(s.finance.ledger.at(-1).rate,20);});
test('disabled period does not gain yield or catch up later',()=>{const s=fresh();deposit(s,'savings',10000);plan(s);C.configureSavings(s,{memberId:'ana',enabled:false,rate:10,period:'month'},adult,'2026-09-28');C.accrueInterest(s,'2026-10-10');C.configureSavings(s,{memberId:'ana',enabled:true,rate:10,period:'month'},adult,'2026-10-10');assert.equal(C.balances(s,'ana').savings,10000);});
test('children cannot change interest rate; malformed rates fail',()=>{const s=fresh();assert.throws(()=>C.configureSavings(s,{memberId:'ana',enabled:true,rate:5,period:'year'},child));for(const rate of [-1,NaN,Infinity,101])assert.throws(()=>plan(s,rate));});
test('interest ledger entries cannot be reversed with generic correction',()=>{const s=fresh();deposit(s,'savings',10000);plan(s);C.accrueInterest(s,'2026-10-03');assert.throws(()=>C.reverseMoney(s,s.finance.ledger.at(-1).id,'test',adult));});
test('projection handles weekly monthly yearly periods explicitly',()=>{assert.equal(C.savingsProjection(10000,10,'month',30),11000);assert.equal(C.savingsProjection(10000,10,'year',365),11000);assert.equal(C.savingsProjection(10000,10,'week',14),12100);});
test('band inclusive boundaries, missing bands and unlimited band',()=>{for(const [p,c] of [[0,0],[19,0],[20,200],[39,200],[40,500],[900,500]])assert.equal(C.tierFor(tiers,p).cents,c);assert.equal(C.tierFor(tiers,-1),null);assert.equal(C.tierFor([{min:2,max:4,cents:10}],5),null);});
test('overlap and invalid ranges rejected, disjoint gaps accepted',()=>{assert.throws(()=>C.validateTiers([{min:0,max:20,cents:100},{min:20,max:null,cents:200}]));assert.throws(()=>C.validateTiers([{min:2,max:1,cents:0}]));assert.throws(()=>C.validateTiers([{min:0,max:null,cents:-1}]));assert.equal(C.validateTiers([{min:5,max:null,cents:0},{min:0,max:3,cents:10}]).length,2);});
test('tier allowance waits for completed week and selected next-week payday',()=>{const s=fresh();configure(s,{payDay:2});pts(s,21);C.syncAllowanceDues(s,'2026-10-06');assert.equal(s.finance.dues.length,0);C.syncAllowanceDues(s,'2026-10-07');assert.equal(s.finance.dues[0].cents,200);assert.equal(s.finance.dues[0].week,'2026-09-28');});
test('point band payout recalculates pending, splits cents and pays once',()=>{const s=fresh();configure(s);pts(s,19);C.syncAllowanceDues(s,'2026-10-05');const d=s.finance.dues[0];pts(s,40);C.payAllowance(s,d.id,adult,'2026-10-05');assert.equal(d.cents,500);assert.equal(C.balances(s,'ana').savings,250);assert.equal(C.balances(s,'ana').available,250);assert.equal(C.payAllowance(s,d.id,adult,'2026-10-05'),false);C.validateState(s);});
test('zero payout is completed without zero-value money entry',()=>{const s=fresh();configure(s);pts(s,-3);C.syncAllowanceDues(s,'2026-10-05');C.payAllowance(s,s.finance.dues[0].id,adult,'2026-10-05');assert.equal(s.finance.dues[0].status,'skipped');assert.equal(s.finance.ledger.length,0);C.validateState(s);});
test('paid money remains fixed after points or configuration correction',()=>{const s=fresh();configure(s);pts(s,21);C.syncAllowanceDues(s,'2026-10-05');const d=s.finance.dues[0];C.payAllowance(s,d.id,adult,'2026-10-05');pts(s,40);assert.equal(C.allowanceQuote(s,d).cents,200);});
test('alternating weeks follow explicit cycle anchor',()=>{const s=fresh();presence(s);assert.equal(C.presenceOn(s,'ana','2026-10-04').present,true);assert.equal(C.presenceOn(s,'ana','2026-10-05').present,false);assert.equal(C.presenceOn(s,'ana','2026-10-12').present,true);});
test('2+2+3 alternates a balanced fourteen-day pattern',()=>{const a=C.presencePattern('223');assert.deepEqual(a,[true,true,false,false,true,true,true,false,false,true,true,false,false,false]);assert.equal(a.filter(Boolean).length,7);assert.deepEqual(C.presencePattern('223',false),a.map(v=>!v));});
test('vacation exception overrides both repeating cycle and one-off absence',()=>{const s=fresh();presence(s);s.absences.push({id:'absence-t',memberId:'ana',from:'2026-10-05',to:'2026-10-08',reason:'Fuera',active:true});C.setPresenceOverride(s,{memberId:'ana',from:'2026-10-05',to:'2026-10-07',present:true,reason:'Vacaciones'},adult,today);assert.equal(C.presenceOn(s,'ana','2026-10-06').present,true);assert.equal(C.presenceOn(s,'ana','2026-10-08').present,false);});
test('overlapping exceptions rejected; end dates inclusive',()=>{const s=fresh();C.setPresenceOverride(s,{memberId:'ana',from:'2026-10-05',to:'2026-10-07',present:false,reason:'Viaje'},adult,today);assert.throws(()=>C.setPresenceOverride(s,{memberId:'ana',from:'2026-10-07',to:'2026-10-09',present:true,reason:'Casa'},adult,today));assert.equal(C.presenceOn(s,'ana','2026-10-07').present,false);assert.equal(C.presenceOn(s,'ana','2026-10-08').present,true);});
test('away tasks are excused, not penalized, and excluded from target',()=>{const s=fresh(),w=pts(s,0);presence(s,'custom',{cycle:[false]});const st=C.stats(w,'ana');assert.equal(st.target,0);assert.equal(st.points,0);assert.ok(w.tasks.filter(t=>t.memberId==='ana').every(t=>t.status==='excused'));});
test('completed tasks and closed weeks survive residence changes',()=>{const s=fresh(),old=JSON.stringify(s.weeks.find(w=>w.status==='closed')),w=s.weeks.find(w=>w.start==='2026-09-28'),t=w.tasks.find(t=>t.memberId==='ana'&&t.status==='done');presence(s,'custom',{cycle:[false]});assert.equal(t.status,'done');assert.equal(JSON.stringify(s.weeks.find(w=>w.status==='closed')),old);});
test('removing presence rule restores previous task status',()=>{const s=fresh(),w=pts(s,0),p=presence(s,'custom',{cycle:[false]});C.cancelPresence(s,p.id,adult);assert.ok(w.tasks.filter(t=>t.memberId==='ana').every(t=>t.status==='pending'));});
test('presence permission, cycle length and retroactive config validation',()=>{const s=fresh();assert.throws(()=>C.presencePattern('custom',true,[]));assert.throws(()=>C.presencePattern('custom',true,Array(57).fill(true)));assert.throws(()=>presence(s,'alternate',{from:'2026-09-21'}));assert.throws(()=>C.configurePresence(s,{memberId:'ana'},child));});
test('food icons are semantic and library insertion is idempotent',()=>{const s=fresh();assert.notEqual(C.foodIcon('Tomate'),C.foodIcon('Pollo'));assert.notEqual(C.foodIcon('Leche'),C.foodIcon('Huevos'));const n=s.recipes.length;assert.equal(C.addRecipeLibrary(s),0);assert.equal(s.recipes.length,n);});
test('stock matching combines normalised singular/plural quantities',()=>{const s=fresh();s.pantry=[{id:'p',name:'Patata',quantity:1,unit:'kg',category:'Fruta y verdura',expires:''}];assert.equal(C.stock(s,'Patatas','g'),1000);});
test('ingredients become shopping items and repeated request is idempotent',()=>{const s=fresh();s.shopping=[];s.pantry=[];const r=s.recipes.find(r=>r.id==='pasta');C.addMissing(s,[{recipeId:r.id,servings:8}]);const pasta=s.shopping.find(x=>x.name==='Pasta');assert.equal(C.quantity(pasta.quantity).n,800);const before=JSON.stringify(s.shopping);C.addMissing(s,[{recipeId:r.id,servings:8}]);assert.equal(JSON.stringify(s.shopping),before);});
test('manual amounts are not lost; they are added for review once',()=>{const s=fresh();s.shopping=[];s.pantry=[];const r=s.recipes[0];r.ingredients=[{name:'Sal',quantity:'al gusto',category:'Despensa'}];C.addMissing(s,[{recipeId:r.id,servings:4}]);C.addMissing(s,[{recipeId:r.id,servings:4}]);assert.equal(s.shopping.length,1);assert.equal(s.shopping[0].needsReview,true);});
test('photos survive catalog and recipe shopping, hostile URLs rejected',()=>{const s=fresh(),photo='data:image/jpeg;base64,YQ==';C.upsertFood(s,{name:'Pasta',photo,store:'Lidl',product:'Mi pasta',category:'Despensa'});s.shopping=[];s.pantry=[];C.addMissing(s,[{recipeId:'pasta',servings:4}]);assert.equal(s.shopping.find(x=>x.name==='Pasta').photo,photo);for(const p of ['https://evil/photo','data:image/svg+xml;base64,YQ==','javascript:alert(1)'])assert.throws(()=>C.photoGuard(p));C.validateState(s);});
