/* La Homa 5 - responsive navigation, reviewed actions and everyday workflows. */
const web5={initialHash:location.hash,initializedRoute:false,routeApplying:false,lastRoute:'',modalInitial:'',modalDirty:false,queued:null,shoppingList:'groceries',diet:'all',wizard:null,objectURLs:new Map()};
const t5=(k,v)=>window.HomaI18n?window.HomaI18n.t(k,v):k;
function groups5(){return[{id:'home',name:t5('navHome'),icon:'house',views:['home','inbox','notifications']},{id:'tasks',name:t5('navTasks'),icon:'tasks',views:['tasks','routines','history']},{id:'calendar',name:t5('navCalendar'),icon:'calendar',views:['calendar','events','organize']},{id:'recipes',name:t5('navKitchen'),icon:'chef',views:['recipes','shopping','pantry']},{id:'family',name:t5('navFamily'),icon:'users',views:['family','member','money','rewards','settings']}];}
const GROUPS5=groups5();
const CHILD_VIEWS5=['member','tasks','routines','money','rewards','events','calendar','kitchen'];
function viewAllowed5(v){return isAdult()||CHILD_VIEWS5.includes(v);}
function group5(){const G=groups5();return G.find(g=>g.views.includes(ui.view))||G[0];}
function currentRoute5(){const p=new URLSearchParams();if(ui.view==='member'&&ui.memberId)p.set('person',ui.memberId);if(ui.view==='recipes'&&ui.recipeTab!=='recipes')p.set('tab',ui.recipeTab);if(ui.view==='tasks'&&ui.taskTab!=='assignments')p.set('tab',ui.taskTab);return '#/'+ui.view+(p.size?'?'+p:'');}
function writeRoute5(replace=false){if(web5.routeApplying||access.blocked)return;const r=currentRoute5();if(r===web5.lastRoute)return;try{history[replace?'replaceState':'pushState']({homa:true},'',r);web5.lastRoute=r;}catch(_){web5.lastRoute=r;}}
function readRoute5(){if(access.blocked)return;const [path,query]=location.hash.replace(/^#\/?/,'').split('?');if(!path||path.includes('='))return;const valid=[...navigation().map(x=>x[0]),'member','settings','inbox','notifications'];if(!valid.includes(path))return;web5.routeApplying=true;ui.view=viewAllowed5(path)?path:'member';const q=new URLSearchParams(query||'');if(ui.view==='member')ui.memberId=isAdult()&&state.members.some(m=>m.id===q.get('person'))?q.get('person'):actor.memberId||activeMembers()[0]?.id;if(ui.view==='recipes'&&['recipes','menu','ingredients'].includes(q.get('tab')))ui.recipeTab=q.get('tab');if(ui.view==='tasks'&&['assignments','templates'].includes(q.get('tab')))ui.taskTab=q.get('tab');render();web5.lastRoute=currentRoute5();web5.routeApplying=false;}
window.addEventListener('popstate',()=>{const destination=location.hash;if($('#modal')?.open&&!closeModal()){try{history.replaceState({homa:true},'',web5.lastRoute);}catch(_){}web5.queued=()=>{try{history.replaceState({homa:true},'',destination);}catch(_){}readRoute5();};return;}readRoute5();});
function guideDraft(){
 if(ui.guide)return ui.guide;
 const adult=state.members.find(m=>m.role==='adult'&&m.active!==false);
 const given=String(adult?.name||'');
 ui.guide={step:0,familyName:state.settings.familyName||'',adultName:given==='Adulto'?'':given,people:[{name:'',role:'member',email:''}],pets:[{name:'',species:'perro'}]};
 return ui.guide;
}
function readGuide(form){
 const g=guideDraft();if(!form)return g;
 if(form.elements.familyName)g.familyName=form.elements.familyName.value;
 if(form.elements.adultName)g.adultName=form.elements.adultName.value;
 const people=[...form.querySelectorAll('[data-guide-person]')].map(row=>({name:row.querySelector('[name=personName]').value,role:row.querySelector('[name=personRole]').value,email:(row.querySelector('[name=personEmail]')?.value||'').trim().toLowerCase()}));
 const pets=[...form.querySelectorAll('[data-guide-pet]')].map(row=>({name:row.querySelector('[name=petName]').value,species:row.querySelector('[name=petSpecies]').value}));
 if(people.length)g.people=people;if(pets.length)g.pets=pets;return g;
}
function finishGuide(){
 const g=guideDraft(),family=g.familyName.trim(),adultName=g.adultName.trim();
 if(!family||!adultName)throw new Error(t5('guideNeedNames'));
 const petEmoji={perro:'\u{1F436}',gato:'\u{1F431}',otro:'\u{1F43E}'};
 const ok=transact(s=>{
  s.settings.familyName=family.slice(0,80);s.settings.familyReady=true;
  const adult=s.members.find(m=>m.role==='adult'&&m.active!==false);if(adult)adult.name=adultName.slice(0,80);
  let n=s.members.length;
  for(const p of g.people){const name=p.name.trim();if(!name)continue;const email=String(p.email||'').trim().toLowerCase();s.members.push({id:C.uid('member'),name:name.slice(0,80),role:p.role==='adult'?'adult':'member',avatar:p.role==='adult'?'\u{1F9D1}':'\u{1F9D2}',color:colors[n%colors.length],age:null,active:true,email:email||'',inviteStatus:'none'});n++;}
  for(const p of g.pets){const name=p.name.trim();if(!name)continue;const species=['perro','gato','otro'].includes(p.species)?p.species:'otro';s.members.push({id:C.uid('member'),name:name.slice(0,80),role:'pet',species,avatar:petEmoji[species],color:colors[n%colors.length],age:null,active:true});n++;}
  const w=s.weeks.find(w=>w.status==='open')||s.weeks.at(-1);
  if(w)for(const m of s.members){const shot=C.memberSnapshot(m),snap=w.members.find(x=>x.id===m.id);if(snap)Object.assign(snap,shot);else w.members.push(shot);}
 },t5('familyReady'));
 if(!ok)return;
 ui.guide=null;ui.view='home';ui.tour={step:0};render();
 if(access.mode==='cloud'&&typeof canManageInvites==='function'&&canManageInvites()){
  const pending=state.members.filter(m=>m.active!==false&&m.role!=='pet'&&m.email&&m.inviteStatus!=='joined'&&m.userId!==access.user?.id);
  if(pending.length){
   queueMicrotask(async()=>{
    try{
     for(const m of pending){
      const inv=await window.HomaCloudTransport.invite(m.email,m.id,m.role==='adult'?'adult':'child');
      transact(s=>{const x=s.members.find(y=>y.id===m.id);if(x)x.inviteStatus='pending';},null);
      showInviteResult(inv,m.name);
     }
    }catch(err){toast(err.message||t5('invitesCreateFail'),true);}
   });
  }
 }
}
function renderFamilyGuide(){
 const g=guideDraft(),step=g.step,titles=[t5('guideTitle0'),t5('guideTitle1'),t5('guideTitle2')];
 const body=step===0?`${field(t5('familyName'),'familyName',g.familyName,'text',`required maxlength="80" placeholder="${esc(t5('familyPh'))}"`)}${field(t5('adultName'),'adultName',g.adultName,'text','required maxlength="80"')}<p class="small muted">${esc(t5('guideAdultHint'))}</p>`
  :step===1?`<p class="small muted mb">${esc(t5('guidePeopleHint'))}</p><p class="tiny muted mb">${esc(t5('guideEmailHint'))}</p>${g.people.map((p,i)=>`<div class="guide-person" data-guide-person><div class="guide-row"><label class="field"><span>${esc(t5('personName'))}</span><input name="personName" value="${esc(p.name)}" maxlength="80"></label><label class="field"><span>${esc(t5('personIs'))}</span><select name="personRole"><option value="member" ${p.role!=='adult'?'selected':''}>${esc(t5('child'))}</option><option value="adult" ${p.role==='adult'?'selected':''}>${esc(t5('adult'))}</option></select></label>${iconBtn('trash','guide-remove',t5('remove'),`data-kind="person" data-index="${i}"`)}</div><label class="field"><span>${esc(t5('optionalEmail'))}</span><input name="personEmail" type="email" maxlength="254" value="${esc(p.email||'')}" placeholder="${esc(t5('optionalEmailPh'))}"></label></div>`).join('')}${btn(t5('addPerson'),'guide-add','data-kind="person"','secondary','plus')}`
  :`<p class="small muted mb">${esc(t5('guidePetsHint'))}</p>${g.pets.map((p,i)=>`<div class="guide-row" data-guide-pet><label class="field"><span>${esc(t5('personName'))}</span><input name="petName" value="${esc(p.name)}" maxlength="80" placeholder="Coco"></label><label class="field"><span>${esc(t5('animal'))}</span><select name="petSpecies"><option value="perro" ${p.species==='perro'?'selected':''}>${esc(t5('dog'))}</option><option value="gato" ${p.species==='gato'?'selected':''}>${esc(t5('cat'))}</option><option value="otro" ${p.species==='otro'?'selected':''}>${esc(t5('other'))}</option></select></label>${iconBtn('trash','guide-remove',t5('remove'),`data-kind="pet" data-index="${i}"`)}</div>`).join('')}${btn(t5('addPet'),'guide-add','data-kind="pet"','secondary','plus')}`;
 $('#app').innerHTML=`<div class="auth-layout"><section class="auth-story"><div class="brand"><div class="brand-mark">${icon('house')}</div><span>La <span style="color:var(--purple)">Homa</span><small>${esc(t5('brandSub'))}</small></span></div><span class="auth-eyebrow">${esc(t5('guideEyebrow'))}</span><h1>${esc(t5('guideStoryTitle'))}</h1><p>${esc(t5('guideStoryText'))}</p><label class="field mt"><span>${esc(t5('chooseLang'))}</span><select data-change="app-locale" aria-label="${esc(t5('chooseLang'))}">${window.HomaI18n?window.HomaI18n.langOptions(window.HomaI18n.getLocale()):'<option value="es">Español</option>'}</select></label></section><section class="auth-panel"><form id="family-guide" class="auth-card"><div class="guide-steps">${[0,1,2].map(i=>`<span class="${i<=step?'on':''}"></span>`).join('')}</div><span class="pill green">${esc(t5('guideStep',{n:step+1}))}</span><h2>${esc(titles[step])}</h2>${body}<div class="guide-actions">${step?btn(t5('back'),'guide-back','','secondary'):''}<button type="submit" class="btn primary">${step===2?esc(t5('enterHome')):esc(t5('continue'))}</button></div></form></section></div>`;
}

const TOUR_STEPS=[{view:'home',title:'tour1Title',text:'tour1Text'},{view:'family',title:'tour2Title',text:'tour2Text'},{view:'tasks',title:'tour3Title',text:'tour3Text'},{view:'calendar',title:'tour4Title',text:'tour4Text'},{view:'recipes',title:'tour5Title',text:'tour5Text'},{view:'money',title:'tour6Title',text:'tour6Text'}];
function clearTour(persist){ui.tour=null;if(persist)transact(s=>{s.settings.tutorialDismissed=true;},null);}
function renderTour(){
 if(!ui.tour||access.blocked||!state.settings.familyReady||state.settings.tutorialDismissed)return;
 const step=Math.max(0,Math.min(ui.tour.step|0,TOUR_STEPS.length-1));
 const item=TOUR_STEPS[step];
 if(ui.view!==item.view){ui.view=item.view;}
 const last=step===TOUR_STEPS.length-1;
 const progress=[...Array(TOUR_STEPS.length)].map((_,i)=>`<span class="${i<=step?'on':''}"></span>`).join('');
 let layer=document.querySelector('.tour-layer');
 if(!layer){layer=document.createElement('div');layer.className='tour-layer';layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','false');document.body.appendChild(layer);}
 layer.innerHTML=`<div class="tour-card"><div class="tour-progress">${progress}</div><p class="eyebrow">${esc(t5('tourTitle'))}</p><h2>${esc(t5(item.title))}</h2><p>${esc(t5(item.text))}</p><div class="tour-actions">${btn(t5('tourSkip'),'tour-skip','','ghost small')}${btn(last?t5('tourDone'):t5('tourNext'),'tour-next','','primary small')}</div></div>`;
}
function removeTourDom(){document.querySelector('.tour-layer')?.remove();}

function render(){
  C.ensureWeb5(state);
  if(!access.blocked&&state.settings.familyReady===false&&isAdult()){renderFamilyGuide();return;}
  if(!access.blocked&&!viewAllowed5(ui.view)){ui.view='member';ui.memberId=actor.memberId;}
  renderBefore5();
  if(access.blocked){enhanceAuth5();return;}
  if(ui.view==='kitchen'){writeRoute5();return;}
  const group=group5(),nav=$('.sidebar-nav');
  if(nav){const groups=isAdult()?groups5():[{id:'member',name:t5('navTasks'),icon:'tasks',views:['member','tasks','routines']},{id:'money',name:t5('setupMoney'),icon:'wallet',views:['money']},{id:'rewards',name:'★',icon:'gift',views:['rewards']},{id:'events',name:t5('navCalendar'),icon:'calendar',views:['events','calendar']}];nav.innerHTML=groups.map(g=>`<button type="button" class="nav-link ${g.views.includes(ui.view)?'active':''}" data-action="nav" data-view="${g.id}" ${g.views.includes(ui.view)?'aria-current="page"':''}>${icon(g.icon)}${esc(g.name)}</button>`).join('')+(typeof canSwitchProfiles==='function'&&canSwitchProfiles()?`<div class="nav-label">${esc(t5('navShared'))}</div><button type="button" class="nav-link" data-action="nav" data-view="kitchen">${icon('tablet')}${esc(t5('tabletView'))}</button>`:'');}
  const mobile=$('.bottom-nav');if(mobile){const groups=isAdult()?groups5():[{id:'member',name:t5('navTasks'),icon:'tasks',views:['member','tasks','routines']},{id:'money',name:t5('setupMoney'),icon:'wallet',views:['money']},{id:'rewards',name:'★',icon:'gift',views:['rewards']},{id:'events',name:t5('navCalendar'),icon:'calendar',views:['events','calendar']}];mobile.innerHTML=groups.map(g=>`<button type="button" class="${g.views.includes(ui.view)?'active':''}" data-action="nav" data-view="${g.id}" ${g.views.includes(ui.view)?'aria-current="page"':''}>${icon(g.icon)}<span>${esc(g.name)}</span></button>`).join('');}
  const main=$('#main-content');
  if(main){main.setAttribute('tabindex','-1');let views=isAdult()?group.views.filter(v=>v!=='member'):ui.view==='member'||ui.view==='tasks'||ui.view==='routines'?['member','tasks','routines']:ui.view==='calendar'||ui.view==='events'?['events','calendar']:[];
   if(views.length>1){const labels={home:t5('secOverview'),inbox:t5('secReviews'),notifications:t5('secNotices'),tasks:t5('secMissions'),routines:t5('secRoutines'),history:t5('secHistory'),calendar:t5('secCalendar'),events:t5('secEvents'),organize:t5('secOrganize'),recipes:t5('secRecipes'),shopping:t5('secShopping'),pantry:t5('secPantry'),family:t5('secPeople'),money:t5('secMoney'),rewards:t5('secRewards'),settings:t5('secSettings'),member:t5('secMyDay')};main.insertAdjacentHTML('afterbegin',`<nav class="section-nav" aria-label="${esc(t5('withinSection',{name:group.name}))}">${views.map(v=>`<button class="${ui.view===v?'active':''}" type="button" data-action="nav" data-view="${v}" ${ui.view===v?'aria-current="page"':''}>${esc(labels[v])}${v==='inbox'&&C.approvalItems(state).length?`<span class="pill">${C.approvalItems(state).length}</span>`:''}</button>`).join('')}</nav>`);}
   if(ui.view==='home'&&isAdult())enhanceHome5(main);
  }
  if(!isAdult())$('.sidebar-bottom [data-view=settings]')?.remove();
  if(isAdult()){const bar=$('.topbar>.flex');if(bar)bar.insertAdjacentHTML('afterbegin',`<button class="icon-btn notification-button" type="button" data-action="nav" data-view="inbox" aria-label="${esc(t5('pendingReviews',{n:C.approvalItems(state).length}))}">${icon('check')}${C.approvalItems(state).length?`<span>${C.approvalItems(state).length}</span>`:''}</button>`);}
  let skip=document.querySelector('.skip-content');if(!skip){skip=document.createElement('a');skip.href='#main-content';skip.className='skip-content';skip.textContent=t5('skipContent');document.body.prepend(skip);}
  if(!web5.initializedRoute){web5.initializedRoute=true;if(web5.initialHash.startsWith('#/')){try{history.replaceState({},'',web5.initialHash);}catch(_){}readRoute5();return;}}
  writeRoute5();
  if(ui.tour&&!state.settings.tutorialDismissed&&state.settings.familyReady)renderTour();else removeTourDom();
}
function nav(view){if(view==='meeting')view='home';if(!viewAllowed5(view))view='member';if(view==='member'&&!isAdult())ui.memberId=actor.memberId;if(view==='kitchen'){enterKitchen();return;}ui.view=view;render();window.scrollTo({top:0,behavior:'auto'});$('#main-content')?.focus({preventScroll:true});}
function modalSnapshot5(){const form=$('#modal-form');if(!form)return '';return JSON.stringify([...form.querySelectorAll('input,select,textarea')].map(e=>[e.name,e.type==='checkbox'||e.type==='radio'?e.checked:e.value]));}
function openModal(title,body,submit=null,ctx={}){web5.modalDirty=false;web5.modalInitial='';openModalBefore5(title,body,submit,ctx);queueMicrotask(()=>{web5.modalInitial=modalSnapshot5();});}
function closeModal(force=false){
 const d=$('#modal');if(!d?.open)return true;
 if(!force&&modalSubmit&&web5.modalInitial&&modalSnapshot5()!==web5.modalInitial){if(!d.querySelector('.discard-warning'))d.querySelector('.modal-header').insertAdjacentHTML('afterend',`<div class="discard-warning" role="alert"><p><b>${esc(t5('unsavedTitle'))}</b> ${esc(t5('unsavedText'))}</p><div class="flex wrap">${btn(esc(t5('keepEditing')),'web5-keep','','primary small')}${btn(esc(t5('discardChanges')),'web5-discard','','danger small')}</div></div>`);d.scrollTop=0;d.querySelector('[data-action=web5-keep]')?.focus();return false;}
 closeModalBefore5();web5.modalInitial='';web5.modalDirty=false;return true;
}
function enhanceHome5(main){
 const children=activeMembers().filter(m=>m.role==='member'),present=activeMembers().filter(m=>C.presenceOn(state,m.id,C.iso()).present);
 const note=`<div class="today-presence"><span class="eyebrow">${esc(t5('todayPresence'))}</span><div class="flex wrap">${present.map(m=>`<span class="person-presence">${avatar(m,'small')}${esc(m.name)}</span>`).join('')||`<span>${esc(t5('noPresence'))}</span>`}</div></div>`;
 main.querySelector('.page-heading')?.insertAdjacentHTML('afterend',note);
 if(!state.demo&&!state.settings.onboardingDismissed){const steps=[{done:children.length>0,label:t5('setupPeople'),view:'family'},{done:state.presencePlans.length>0,label:t5('setupPresence'),view:'organize'},{done:state.templates.length>0,label:t5('setupTasks'),view:'tasks'},{done:state.finance.accounts.length>0,label:t5('setupMoney'),view:'money'}];main.querySelector('.today-presence')?.insertAdjacentHTML('afterend',`<section class="setup-panel"><div class="flex between wrap"><h3>${esc(t5('setupTitle'))}</h3>${btn(t5('hideGuide'),'web5-setup-dismiss','','ghost small')}</div><div class="setup-steps">${steps.map((s,i)=>`<button type="button" data-action="nav" data-view="${s.view}"><span>${s.done?icon('check'):i+1}</span>${esc(s.label)}</button>`).join('')}</div><p class="small muted">${esc(t5('setupNote'))}</p></section>`);}
}
function renderInbox5(){if(!isAdult())return empty(esc(t5('emptyAdultOnlyTitle')),esc(t5('emptyAdultOnlyDetail')));const list=C.approvalItems(state);return `${heading(esc(t5('inboxTitle')), esc(t5('inboxSub')),btn(esc(t5('secNotices')),'nav','data-view="notifications"','secondary','calendar'))}<div class="panel">${list.map(x=>`<article class="review-row"><div class="grow"><span class="eyebrow">${esc({task:t5('reviewTypeTask'),correction:t5('reviewTypeCorrection'),spend:t5('reviewTypeSpend'),voucher:t5('reviewTypeVoucher')}[x.type])}</span><h3>${esc(x.title)}</h3><p>${esc(member(x.memberId).name)}${x.note?' \u00b7 '+esc(x.note):''}</p></div><div class="flex wrap">${btn(esc(t5('inboxReview')),'web5-review',`data-id="${esc(x.id)}" data-type="${x.type}" data-week="${x.week||''}"`,'primary small','check')}</div></article>`).join('')||empty(esc(t5('emptyInboxDoneTitle')),esc(t5('emptyInboxDoneDetail')))}</div><section class="settings-group mt"><h3>${esc(t5('recentActivity'))}</h3><p>${esc(t5('recentActivityText'))}</p>${state.houseLog.slice(0,30).map(x=>`<div class="audit-row"><span>${esc(x.action)}</span><time>${esc(new Date(x.at).toLocaleString(localeBcp(),{dateStyle:'short',timeStyle:'short'}))}</time></div>`).join('')||'<p class="mt">'+esc(t5('noChangesYet'))+'</p>'}</section>`;}
function notificationSettings5(){if(!needAdult())return;const n=state.settings.notifications;openModal(t5('whenNotify'),`<p class="dialog-description">${esc(t5('notifModalNote'))}</p>${['enabled','events','checklists','approvals','allowance'].map((k,i)=>`<label class="check-label"><input name="${k}" type="checkbox" ${n[k]?'checked':''}>${esc(t5(['enableNotices','upcomingPlans','pendingPrep','adultReviews','payToConfirm'][i]))}</label>`).join('')}<div class="form-grid">${field(t5('leadMinutes'),'leadMinutes',n.leadMinutes,'number','min="0" max="10080" required')}${field(t5('quietFrom'),'quietStart',n.quietStart,'time','required')}${field(t5('quietUntil'),'quietEnd',n.quietEnd,'time','required')}</div>${footer(esc(t5('savePrefs')))}`,fd=>transact(s=>{s.settings.notifications=Object.fromEntries(['enabled','events','checklists','approvals','allowance'].map(k=>[k,!!fd.get(k)]));Object.assign(s.settings.notifications,{leadMinutes:Number(fd.get('leadMinutes')),quietStart:fd.get('quietStart'),quietEnd:fd.get('quietEnd')});},t5('prefsSaved')));}
function renderNotifications5(){const items=C.reminderItems(state).filter(x=>isAdult()||x.kind!=='adult'&&(!x.memberIds.length||x.memberIds.includes(actor.memberId)));return `${heading(esc(t5('notifTitle')), esc(t5('notifSub')),isAdult()?btn(esc(t5('noticesBtn')),'web5-notification-settings','','secondary','settings'):'')}<div class="note mb">${esc(t5('notifInAppNote'))}</div><div class="panel">${items.map(x=>`<article class="review-row"><div class="grow"><h3>${esc(x.title)}</h3><p>${esc(x.detail)}</p></div>${btn(esc(t5('open')),x.eventId?'ev31-detail':'nav',x.eventId?`data-id="${esc(x.eventId)}"`:`data-view="${x.view}"`,'secondary small','arrow')}</article>`).join('')||empty(esc(t5('emptyNotifTitle')),esc(t5('emptyNotifDetail')))}</div>`;}
function renderTasksV2(){let html=renderTasksBefore5();if(isAdult())html=html.replace('</div></div>','</div></div>');return html+(isAdult()?`<div class="context-toolbar mt">${btn(esc(t5('taskPresets')),'web5-task-presets','','secondary','plus')}</div>`:'');}
function taskForm(id=null,mid=null){taskFormBefore5(id,mid);if(!isAdult())return;const t=state.templates.find(t=>t.id===id),freq=$('#modal [name=frequency]');if(!freq)return;freq.insertAdjacentHTML('beforeend',`<option value="flexible">${esc(t5('freqFlexible'))}</option><option value="monthly">${esc(t5('freqMonthly'))}</option>`);freq.value=t?.frequency||'daily';const grid=freq.closest('.form-grid');grid.insertAdjacentHTML('afterend',`<div class="form-grid mt" id="web5-task-options">${field(t5('quotaWeek'),'quota',t?.quota||3,'number','min="1" max="7" required')}${field(t5('monthDayField'),'monthDay',t?.monthDay||1,'number','min="1" max="28" required')}</div><p class="small muted mt">${esc(t5('flexibleHint'))}</p><label class="check-label"><input name="allowEarly" type="checkbox" ${t?.allowEarly?'checked':''}>${esc(t5('allowEarly'))}</label>`);if(t)$('#modal .modal-footer').insertAdjacentHTML('afterbegin',btn(esc(t5('duplicate')),'web5-task-duplicate',vattr(t.id),'secondary'));}
function eventForm(id=null,d=null,copyId=null,type='family'){
 eventFormBefore5(id,d,copyId,type);if(!isAdult())return;
 const e=state.events.find(e=>e.id===(id||copyId)),root=e?.seriesId?state.events.find(x=>x.id===e.seriesId):null,spec=root?.recurrence||e?.recurrence||{frequency:'none',interval:1,until:C.addDays(e?.date||d||C.iso(),90)};
 const insert=$('#modal .checklist-editor');
 insert?.insertAdjacentHTML('beforebegin',`<section class="recurrence-editor"><h3>${esc(t5('repeatAndNotice'))}</h3>${e?.seriesId&&!copyId?`<div class="note mb">${esc(t5('thisDateInSeries'))} ${btn(esc(t5('editSeries')),'web5-series-edit',vattr(e.seriesId),'secondary small')}</div>`:''}<div class="form-grid">${selectField(t5('repeatField'),'recurrenceFrequency',[{value:'none',label:t5('doesNotRepeat')},{value:'daily',label:t5('everyDay')},{value:'weekly',label:t5('everyWeek')},{value:'monthly',label:t5('everyMonth')}],e?.seriesId&&e.id!==e.seriesId?'none':spec.frequency)}${field(t5('everyNPeriods'),'recurrenceInterval',spec.interval||1,'number','min="1" max="12" required')}${field(t5('repeatUntil'),'recurrenceUntil',spec.until||C.addDays(e?.date||C.iso(),90),'date')}${field(t5('reminderMinutes'),'reminderMinutes',e?.reminderMinutes??state.settings.notifications.leadMinutes,'number','min="0" max="10080" required')}</div>${e?.seriesId&&!copyId?selectField(t5('applyChangesTo'),'seriesScope',[{value:'single',label:t5('thisDateOnly')},{value:'series',label:t5('futureSeries')}],e.id===e.seriesId?'series':'single'):'<input type="hidden" name="seriesScope" value="series">'}<p class="small muted">${esc(t5('recurrenceNote'))}</p></section>`);
}
function renderShoppingV2(){
 const lists=state.shoppingLists.filter(l=>!l.archived);if(!lists.some(l=>l.id===web5.shoppingList))web5.shoppingList='groceries';const all=state.shopping;let html;
 try{state.shopping=all.filter(x=>x.listId===web5.shoppingList);html=renderShoppingBefore5();}finally{state.shopping=all;}
 const list=lists.find(l=>l.id===web5.shoppingList),prefix=`<div class="list-toolbar"><label class="field"><span>${esc(t5('activeList'))}</span><select data-change="web5-list" aria-label="${esc(t5('activeList'))}">${selectOptions(lists.map(l=>({value:l.id,label:l.icon+' '+l.name})),web5.shoppingList)}</select></label>${isAdult()?btn(esc(t5('newList')),'web5-list-new','','secondary','plus'):''}${isAdult()&&list.id!=='groceries'?btn(esc(t5('archive')),'web5-list-archive',vattr(list.id),'ghost small'):''}${btn(esc(t5('usuals')),'web5-usual','','secondary','history')}</div>`;
 return prefix+html;
}
function shoppingForm(id){shoppingFormBefore5(id);const x=state.shopping.find(x=>x.id===id);if(!$('#modal-form'))return;$('#modal .modal-footer').insertAdjacentHTML('beforebegin',selectField(t5('saveInList'),'listId',state.shoppingLists.filter(l=>!l.archived).map(l=>({value:l.id,label:l.name})),x?.listId||web5.shoppingList));}
function renderMenu(){return `<div class="menu-tools">${btn(esc(t5('copyPrevWeek')),'web5-menu-copy','','secondary','copy')}${btn(esc(t5('saveThisMenu')),'web5-menu-save','','secondary','heart')}${state.savedMenus.length?btn(esc(t5('savedMenus')),'web5-menu-library','','secondary','book'):''}</div>`+renderMenuBefore5();}
function mealForm(d=null,slot=null,recipeId=null,servings=null){mealFormBefore5(d,slot,recipeId,servings);if(!isAdult())return;const dateInput=$('#modal [name=date]'),n=$('#modal [name=servings]');if(!dateInput||!n)return;const update=()=>{const count=C.menuServings(state,dateInput.value);n.value=Math.max(1,count);let note=$('#meal-presence-note');if(!note){note=document.createElement('p');note.id='meal-presence-note';note.className='note mt';n.closest('.field').insertAdjacentElement('afterend',note);}note.textContent=count?t5('servingsAtHome',{n:count}):t5('nobodyHomeCook');};if(!servings)update();dateInput.addEventListener('change',update);}
function recipeForm(id){recipeFormBefore5(id);if(!isAdult())return;const r=state.recipes.find(x=>x.id===id);$('#modal .modal-footer')?.insertAdjacentHTML('beforebegin',`${field(t5('tagsComma'),'tags',(r?.tags||[]).join(', '),'text',`maxlength="200" placeholder="${esc(t5('tagsPh'))}"`)}${field(t5('recipeSource'),'sourceUrl',r?.sourceUrl||'','url','maxlength="1000"')}<p class="small muted">${esc(t5('tagsNote'))}</p>`);}
function renderRecipes(){let all=state.recipes,html;try{if(web5.diet!=='all')state.recipes=all.filter(r=>(r.tags||[]).includes(web5.diet));html=renderRecipesBefore5();}finally{state.recipes=all;}if(ui.recipeTab==='recipes'){const tags=[...new Set(all.flatMap(r=>r.tags||[]))];html=`<div class="recipe-tools">${isAdult()?btn(esc(t5('importRecipe')),'web5-recipe-import','','secondary','download'):''}<label class="field"><span>${esc(t5('tagLabel'))}</span><select data-change="web5-diet">${selectOptions([{value:'all',label:t5('allTags')},...tags],web5.diet)}</select></label></div>`+html;}return html;}
function recipeImport5(){if(!needAdult())return;openModal(t5('importRecipeTitle'),`${field(t5('recipeLink'),'url','','url','maxlength="1000" placeholder="https://..."')}<div class="mt">${btn(esc(t5('readLink')),'web5-recipe-fetch','','secondary','download')}</div><label class="field mt"><span>${esc(t5('orPasteHtml'))}</span><textarea name="source" maxlength="1000000" rows="6"></textarea></label><div class="note">${esc(t5('importNote'))}</div>${footer(esc(t5('prepareDraft')))}`,fd=>{const recipe=window.HomaRecipeImport.parse(String(fd.get('source')),String(fd.get('url')));closeModal(true);openImportedRecipe5(recipe);return false;});}
function openImportedRecipe5(r){recipeForm();const form=$('#modal-form');for(const k of ['name','servings','minutes','emoji','sourceUrl'])if(form.elements[k])form.elements[k].value=r[k]||({servings:4,minutes:30,emoji:'\u{1F37D}\uFE0F'}[k])||'';form.elements.steps.value=r.steps.join('\n');$('#ingredients-editor').innerHTML=r.ingredients.map(ingredientEditor).join('');web5.modalInitial='imported';toast(t5('draftImported'));}
function fileSection5(e){const files=state.eventFiles.filter(f=>f.eventId===e.id);return `<section class="settings-group mt"><div class="flex between wrap"><div><h3>${esc(t5('eventDocs'))}</h3><p>${esc(t5('eventDocsNote'))}</p></div>${btn(esc(t5('attach')),'web5-file-add',vattr(e.id),'secondary','plus')}</div>${files.map(f=>`<div class="settings-row"><div class="grow"><h4>${esc(f.name)}</h4><p>${Math.ceil(f.size/1024)} KB${f.expires?' \u00b7 '+esc(t5('reviewDeleteOn',{date:f.expires})):''}</p></div>${btn(esc(t5('open')),'web5-file-open',vattr(f.id),'secondary small')}${iconBtn('trash','web5-file-delete',t5('deleteDoc'),vattr(f.id))}</div>`).join('')}</section>`;}
function eventDetail31(id){eventDetailBefore5(id);const e=state.events.find(x=>x.id===id);if(e&&isAdult())$('#modal .modal-body')?.insertAdjacentHTML('beforeend',fileSection5(e));}
function taskPresets5(){if(!needAdult())return;const sets=[[t5('presetBed'),'bed','daily',2],[t5('presetToys'),'blocks','daily',3],[t5('presetTable'),'utensils','daily',3],[t5('presetPlants'),'plant','flexible',4],[t5('presetRoom'),'house','weekly',5],[t5('presetBag'),'book','daily',3]];openModal(t5('startBase'),`<p class="dialog-description">${esc(t5('startBaseNote'))}</p>${sets.map((s,i)=>`<button type="button" class="profile-option" data-action="web5-task-preset" data-index="${i}">${icon(s[1])}<div><b>${esc(s[0])}</b><p>${esc(s[2]==='flexible'?t5('freqFlexible'):s[2]==='weekly'?t5('freqWeekly'):t5('freqDaily'))}</p></div></button>`).join('')}`,null,{presets:sets});}
function renderSettingsV2(){const lang=state.settings.locale||(window.HomaI18n?window.HomaI18n.getLocale():'es');return renderSettingsBefore5()+`<section class="settings-group"><h3>${esc(t5('settingsLang'))}</h3><p>${esc(t5('settingsLangHelp'))}</p><label class="field mt"><span>${esc(t5('lang'))}</span><select data-change="app-locale" aria-label="${esc(t5('chooseLang'))}">${window.HomaI18n?window.HomaI18n.langOptions(lang):'<option value="es">Español</option>'}</select></label></section><section class="settings-group"><h3>${esc(t5('tzNotices'))}</h3><p>${t5('tzFamilyUses',{zone:'|||'}).split('|||').map((part,i)=>i?`<b>${esc(state.settings.timeZone)}</b>${esc(part)}`:esc(part)).join('')}</p><div class="flex wrap mt">${btn(esc(t5('timezoneBtn')),'web5-timezone','','secondary','calendar')}${btn(esc(t5('noticesBtn')),'web5-notification-settings','','secondary','settings')}${btn(esc(t5('howSavedBtn')),'web5-connections','','secondary','link')}</div></section>`;}
function enhanceAuth5(){const f=$('#access-form');if(f&&access.tab==='login'&&!$('.auth-recovery'))f.insertAdjacentHTML('afterend',`<button type="button" class="text-btn auth-recovery" data-action="web5-forgot">${esc(t5('forgotPassword'))}</button>`);}
function resetPassword5(){openModal(t5('recoverAccess'),`${field(t5('yourEmail'),'email','','email','required maxlength="254" autocomplete="email"')}${footer(esc(t5('sendLink')))}`,async fd=>{const client=await cloudClient();const {error}=await client.auth.resetPasswordForEmail(fd.get('email'),{redirectTo:location.origin+location.pathname+'?recovery=1'});if(error)throw error;toast(t5('resetSent'));return true;});}
async function web5Action(a,d,el,event){
 switch(a){
 case 'event-delete':{if(!needAdult())return true;const ev=state.events.find(x=>x.id===d.id);openModal(t5('deleteEvent'),`<p class="dialog-description">${esc(t5('deleteEventBody'))}</p>${ev?.seriesId?selectField(t5('scopeField'),'scope',[{value:'single',label:t5('thisDateOnly')},{value:'series',label:t5('allFutureSeries')}],'single'):'<input name="scope" type="hidden" value="single">'}${footer(esc(t5('delete')))}`,fd=>transact(st=>C.deleteEventSeries(st,d.id,fd.get('scope'),actor),t5('eventDeleted')));return true;}
 case 'web5-keep':web5.queued=null;$('.discard-warning')?.remove();return true;
 case 'web5-discard':closeModal(true);if(web5.queued){const fn=web5.queued;web5.queued=null;fn();}return true;
 case 'nav':if($('#modal').open&&!closeModal()){web5.queued=()=>nav(d.view);return true;}return false;
 case 'web5-review':{
  const x=C.approvalItems(state).find(x=>x.id===d.id&&x.type===d.type);if(!x)return true;
  if(x.type==='task'){taskStateModal(x.week,x.id);return true;}
  if(x.type==='correction'){openModal(t5('reviewCorrection'),`<p class="dialog-description"><b>${esc(x.title)}</b><br>${esc(member(x.memberId).name)}${x.note?'<br>'+esc(x.note):''}</p><div class="note">${esc(t5('scoreUnchangedReview'))}</div><div class="modal-footer">${btn(esc(t5('reject')),'web5-review-resolve',`data-id="${x.id}" data-approve="no"`,'secondary')}${btn(esc(t5('approveCorrection')),'web5-review-resolve',`data-id="${x.id}" data-approve="yes"`,'primary')}</div>`);return true;}
  if(x.type==='spend'){ui.moneyMember=x.memberId;nav('money');return true;}if(x.type==='voucher'){ui.rewardTab='vouchers';nav('rewards');return true;}return true;
 }
 case 'web5-task-review':{openModal(t5('askReview'),`<p class="dialog-description">${esc(t5('reviewRequestNote'))}</p><label class="field"><span>${esc(t5('whatToExplain'))}</span><textarea name="note" maxlength="500"></textarea></label>${footer(esc(t5('sendRequest')))}`,fd=>transact(s=>C.requestTaskReview(s,d.week,d.id,actor,fd.get('note')),t5('requestSent')));return true;}
 case 'web5-review-resolve':if(transact(s=>C.resolveTaskReview(s,d.id,d.approve==='yes',actor),t5('reviewResolved')))closeModal(true);return true;
 case 'web5-setup-dismiss':transact(s=>s.settings.onboardingDismissed=true);return true;
 case 'tour-skip':clearTour(true);removeTourDom();render();return true;
 case 'tour-next':{if(!ui.tour)return true;ui.tour.step=(ui.tour.step|0)+1;if(ui.tour.step>=TOUR_STEPS.length){clearTour(true);removeTourDom();}render();return true;}
 case 'guide-skip':{const g=readGuide($('#family-guide'));const family=(g.familyName||state.settings.familyName||'La Homa').trim()||'La Homa';const adultName=(g.adultName||state.members.find(m=>m.role==='adult')?.name||'Adulto').trim()||'Adulto';g.familyName=family;g.adultName=adultName;g.step=2;try{finishGuide();clearTour(true);removeTourDom();render();}catch(err){toast(err.message,true);}return true;}
 case 'web5-notification-settings':notificationSettings5();return true;
 case 'web5-task-presets':taskPresets5();return true;
 case 'web5-task-preset':{const s=modalContext.presets[Number(d.index)];closeModal(true);taskForm();const f=$('#modal-form');f.elements.title.value=s[0];f.elements.icon.value=[...f.elements.icon.options].some(o=>o.value===s[1])?s[1]:'house';f.elements.frequency.value=s[2];f.elements.points.value=s[3];return true;}
 case 'web5-task-duplicate':{const t=state.templates.find(x=>x.id===d.id);if(!t)return true;closeModal(true);taskForm();const f=$('#modal-form');for(const k of ['title','description','points','frequency','category','icon','quota','monthDay'])if(f.elements[k]&&t[k]!=null)f.elements[k].value=k==='title'?t5('copyOf',{title:t[k]}):t[k];f.querySelectorAll('[name=members]').forEach(x=>x.checked=t.memberIds.includes(x.value));return true;}
 case 'web5-series-edit':{if(!closeModal()){web5.queued=()=>eventForm(d.id);return true;}eventForm(d.id);return true;}
 case 'web5-list-new':openModal(t5('newList'),`${field(t5('fieldName'),'name','','text',`required maxlength="60" placeholder="${esc(t5('listNamePh'))}"`)}${field(t5('anIcon'),'icon','\u{1F6D2}','text','required maxlength="20"')}${footer(esc(t5('createList')))}`,fd=>transact(s=>{web5.shoppingList=C.addShoppingList(s,fd.get('name'),actor,fd.get('icon')).id;},t5('listCreated')));return true;
 case 'web5-list-archive':confirmDialog(t5('archiveList'),t5('archiveListBody'),()=>transact(s=>C.archiveShoppingList(s,d.id,actor),t5('listArchived')));return true;
 case 'web5-usual':{const items=[...new Map(state.usualProducts.slice().reverse().map(x=>[C.foodKey(x.name),x])).values()].slice(0,30);openModal(t5('buyAgain'),items.map(x=>`<button type="button" class="profile-option" data-action="web5-usual-add" data-id="${x.id}">${foodMedia(x)}<span>${esc(x.name)}<small class="muted"> \u00b7 ${esc(x.quantity)}</small></span></button>`).join('')||empty(esc(t5('emptyUsualTitle')),esc(t5('emptyUsualDetail'))));return true;}
 case 'web5-usual-add':{transact(s=>{const x=s.usualProducts.find(x=>x.id===d.id);if(!x)throw new Error(t5('productUnavailable'));if(s.shopping.some(y=>!y.checked&&y.listId===web5.shoppingList&&C.foodKey(y.name)===C.foodKey(x.name)))throw new Error(t5('alreadyPendingList'));s.shopping.push({...x,id:C.uid('shop'),checked:false,listId:web5.shoppingList});},t5('addedToActiveList'));closeModal(true);return true;}
 case 'shopping-clear':confirmDialog(t5('clearThisList'),t5('clearListBody'),()=>transact(s=>{s.shopping=s.shopping.filter(x=>x.listId!==web5.shoppingList||!x.checked);},t5('listCleared')));return true;
 case 'shopping-copy':{const text=state.shoppingLists.find(l=>l.id===web5.shoppingList)?.name+'\n\n'+state.shopping.filter(x=>x.listId===web5.shoppingList&&!x.checked).map(x=>'[ ] '+x.name+' - '+x.quantity).join('\n');try{await navigator.clipboard.writeText(text);toast(t5('listCopied'));}catch(_){downloadFile('la-homa-lista.txt',text);}return true;}
 case 'web5-menu-copy':openModal(t5('reuseMenu'),`<p class="dialog-description">${esc(t5('copyMenuNote'))}</p><label class="check-label"><input type="checkbox" name="adjust" checked>${esc(t5('adjustServingsPresence'))}</label>${footer(esc(t5('copyAndReview')))}`,fd=>{let r;const ok=transact(s=>{r=C.copyMenu(s,C.addDays(ui.menuStart,-7),ui.menuStart,actor,!!fd.get('adjust'));});if(ok)toast(t5('menuCopyToast',{copied:r.copied,skipped:r.skipped}));return ok;});return true;
 case 'web5-menu-save':openModal(t5('saveUsualMenu'),`${field(t5('fieldName'),'name','','text',`required maxlength="80" placeholder="${esc(t5('menuNamePh'))}"`)}${footer(esc(t5('saveMenu')))}`,fd=>transact(s=>C.saveMenu(s,ui.menuStart,fd.get('name'),actor),t5('menuSaved')));return true;
 case 'web5-menu-library':openModal(t5('yourMenus'),state.savedMenus.map(m=>`<button type="button" class="profile-option" data-action="web5-menu-apply" data-id="${m.id}"><b>${esc(m.name)}</b><span>${esc(t5('dishesN',{n:m.plans.length}))}</span></button>`).join('')+`<div class="note mt">${esc(t5('menuLibraryNote'))}</div>`);return true;
 case 'web5-menu-apply':if(transact(s=>C.applySavedMenu(s,d.id,ui.menuStart,actor),t5('menuApplied')))closeModal(true);return true;
 case 'web5-recipe-import':recipeImport5();return true;
 case 'web5-recipe-fetch':{const url=$('#modal [name=url]').value;if(!cloudConfigured())throw new Error(t5('recipeLinkNeedsCloud'));el.disabled=true;try{const result=await cloudFunction5('recipe-import',{url});$('#modal [name=source]').value=JSON.stringify(result.recipe);}finally{el.disabled=false;}return true;}
 case 'web5-file-add':{
  if(!needAdult())return true;openModal(t5('attachDoc'),`<input type="hidden" name="eventId" value="${esc(d.id)}"><label class="field"><span>${esc(t5('fileTypesMax'))}</span><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt" required></label>${field(t5('fileExpiryOpt'),'expires','','date')}${footer(esc(t5('saveDoc')))}`,async fd=>{const file=fd.get('file');if(!file?.size||file.size>5*1024*1024)throw new Error(t5('fileMax5mb'));if(!['application/pdf','image/jpeg','image/png','image/webp','text/plain'].includes(file.type))throw new Error(t5('fileFormatBad'));const id=C.uid('asset');await window.HomaAssets.put(KEY,id,file);const ok=transact(s=>s.eventFiles.push({id,eventId:d.id,name:file.name.slice(0,200),mime:file.type,size:file.size,expires:fd.get('expires')||'',createdAt:new Date().toISOString()}),t5('docSaved'));if(!ok)await window.HomaAssets.remove(KEY,id);return ok;});return true;
 }
 case 'web5-file-open':{if(!needAdult())return true;const f=state.eventFiles.find(f=>f.id===d.id);const blob=await window.HomaAssets.get(KEY,d.id);if(!blob)throw new Error(t5('fileNotOnDevice'));const url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download=f.name;ael.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return true;}
 case 'web5-file-delete':{if(!needAdult())return true;confirmDialog(t5('deleteDoc'),t5('deleteDocBody'),async()=>{const ok=transact(s=>s.eventFiles=s.eventFiles.filter(f=>f.id!==d.id));if(ok)await window.HomaAssets.remove(KEY,d.id);return ok;},t5('delete'));return true;}
 case 'backup-export':{if(!needAdult())return true;const bundle=await window.HomaAssets.exportBundle(KEY,state.eventFiles.map(f=>f.id));downloadFile('la-homa-copia-completa-'+C.iso()+'.json',JSON.stringify({...state,assetBundle:bundle},null,2),'application/json');toast(t5('fullBackupCreated'));return true;}
 case 'web5-forgot':resetPassword5();return true;
 case 'guide-back':{const g=readGuide($('#family-guide'));g.step=Math.max(0,g.step-1);render();return true;}
 case 'guide-add':{const g=readGuide($('#family-guide'));if(d.kind==='pet')g.pets.push({name:'',species:'perro'});else g.people.push({name:'',role:'member',email:''});render();return true;}
 case 'guide-remove':{const g=readGuide($('#family-guide'));const list=d.kind==='pet'?g.pets:g.people;const i=Number(d.index);if(list.length<=1)list[0].name='';else list.splice(i,1);render();return true;}
 case 'web5-timezone':openModal(esc(t5('timezoneTitle')),`${field(t5('timezoneField'),'zone',state.settings.timeZone,'text','required maxlength="80" placeholder="Europe/Madrid"')}<p class="note">${esc(t5('timezoneNote'))}</p>${footer(t5('save'))}`,fd=>transact(s=>{new Intl.DateTimeFormat('es',{timeZone:fd.get('zone')});s.settings.timeZone=fd.get('zone');},t5('timezoneSaved')));return true;
 case 'web5-connections':openModal(esc(t5('howSavedTitle')),`<div class="connection-row"><b>${esc(t5('howSavedDevice'))}</b><span>${esc(t5('howSavedDeviceText'))}</span></div><div class="connection-row"><b>${esc(t5('howSavedAccount'))}</b><span>${esc(cloudConfigured()?(access.mode==='cloud'?t5('howSavedCloudOn'):t5('howSavedCloudReady')):t5('howSavedCloudOff'))}</span></div><div class="connection-row"><b>${esc(t5('howSavedCal'))}</b><span>${esc(t5('howSavedCalText'))}</span></div><div class="connection-row"><b>${esc(t5('howSavedPush'))}</b><span>${esc(t5('howSavedPushText'))}</span></div><p class="note mt">${esc(t5('howSavedBackupNote'))}</p><div class="modal-footer">${btn(esc(t5('understood')),'close','','primary')}</div>`);return true;
 }
 return false;
}
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.change==='member-role'){const pet=el.value==='pet';$('#member-age')?.classList.toggle('hidden',pet);$('#member-species')?.classList.toggle('hidden',!pet);$('#member-email')?.classList.toggle('hidden',pet);}if(el.dataset.change==='web5-list'){web5.shoppingList=el.value;render();}if(el.dataset.change==='web5-diet'){web5.diet=el.value;render();}if(el.dataset.change==='app-locale'&&window.HomaI18n){const code=window.HomaI18n.normalize(el.value);window.HomaI18n.setLocale(code);if(state?.settings){const apply=()=>{state.settings.locale=code;if(typeof queueAccountSave==='function')queueAccountSave(C.copy(state));else if(typeof save==='function')save();};if(typeof transact==='function'&&!access.blocked)transact(s=>{s.settings.locale=code;},'');else apply();}render();}});
document.addEventListener('submit',e=>{if(e.target.id!=='family-guide')return;e.preventDefault();const g=readGuide(e.target);if(g.step===0&&(!g.familyName.trim()||!g.adultName.trim())){toast(t5('guideNeedNames'),true);return;}if(g.step<2){g.step++;render();return;}try{finishGuide();}catch(err){toast(err.message,true);}});
window.addEventListener('beforeunload',e=>{if($('#modal')?.open&&modalSubmit&&web5.modalInitial&&modalSnapshot5()!==web5.modalInitial){e.preventDefault();e.returnValue='';}});
$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});

document.addEventListener('change',e=>{if(e.target.dataset.change==='task-frequency'&&['flexible','monthly'].includes(e.target.value)){document.querySelectorAll('#modal [name=days]').forEach(x=>x.checked=true);const hint=document.querySelector('#frequency-hint');if(hint)hint.textContent=e.target.value==='flexible'?t5('flexibleHintShort'):t5('monthlyHintShort');}});

async function cloudFunction5(name,payload){const client=await cloudClient();const {data,error}=await client.functions.invoke(name,{body:payload});if(error)throw new Error(t5('webServiceFail'));return data;}
