/* La Homa 5 - responsive navigation, reviewed actions and everyday workflows. */
const web5={initialHash:location.hash,initializedRoute:false,routeApplying:false,lastRoute:'',modalInitial:'',modalDirty:false,queued:null,shoppingList:'groceries',diet:'all',wizard:null,objectURLs:new Map()};
const GROUPS5=[{id:'home',name:'Hoy',icon:'house',views:['home','inbox','notifications']},{id:'tasks',name:'Tareas',icon:'tasks',views:['tasks','routines','history']},{id:'calendar',name:'Agenda',icon:'calendar',views:['calendar','events','organize']},{id:'recipes',name:'Cocina',icon:'chef',views:['recipes','shopping','pantry']},{id:'family',name:'Familia',icon:'users',views:['family','member','money','rewards','settings']}];
const CHILD_VIEWS5=['member','tasks','routines','money','rewards','events','calendar','kitchen'];
function viewAllowed5(v){return isAdult()||CHILD_VIEWS5.includes(v);}
function group5(){return GROUPS5.find(g=>g.views.includes(ui.view))||GROUPS5[0];}
function currentRoute5(){const p=new URLSearchParams();if(ui.view==='member'&&ui.memberId)p.set('person',ui.memberId);if(ui.view==='recipes'&&ui.recipeTab!=='recipes')p.set('tab',ui.recipeTab);if(ui.view==='tasks'&&ui.taskTab!=='assignments')p.set('tab',ui.taskTab);return '#/'+ui.view+(p.size?'?'+p:'');}
function writeRoute5(replace=false){if(web5.routeApplying||access.blocked)return;const r=currentRoute5();if(r===web5.lastRoute)return;try{history[replace?'replaceState':'pushState']({homa:true},'',r);web5.lastRoute=r;}catch(_){web5.lastRoute=r;}}
function readRoute5(){if(access.blocked)return;const [path,query]=location.hash.replace(/^#\/?/,'').split('?');if(!path||path.includes('='))return;const valid=[...navigation.map(x=>x[0]),'member','settings','inbox','notifications'];if(!valid.includes(path))return;web5.routeApplying=true;ui.view=viewAllowed5(path)?path:'member';const q=new URLSearchParams(query||'');if(ui.view==='member')ui.memberId=isAdult()&&state.members.some(m=>m.id===q.get('person'))?q.get('person'):actor.memberId||activeMembers()[0]?.id;if(ui.view==='recipes'&&['recipes','menu','ingredients'].includes(q.get('tab')))ui.recipeTab=q.get('tab');if(ui.view==='tasks'&&['assignments','templates'].includes(q.get('tab')))ui.taskTab=q.get('tab');render();web5.lastRoute=currentRoute5();web5.routeApplying=false;}
window.addEventListener('popstate',()=>{const destination=location.hash;if($('#modal')?.open&&!closeModal()){try{history.replaceState({homa:true},'',web5.lastRoute);}catch(_){}web5.queued=()=>{try{history.replaceState({homa:true},'',destination);}catch(_){}readRoute5();};return;}readRoute5();});
function render(){
  C.ensureWeb5(state);if(!access.blocked&&!viewAllowed5(ui.view)){ui.view='member';ui.memberId=actor.memberId;}
  renderBefore5();
  if(access.blocked){enhanceAuth5();return;}
  if(ui.view==='kitchen'){writeRoute5();return;}
  const group=group5(),nav=$('.sidebar-nav');
  if(nav){const groups=isAdult()?GROUPS5:[{id:'member',name:'Mis tareas',icon:'tasks',views:['member','tasks','routines']},{id:'money',name:'Mi dinero',icon:'wallet',views:['money']},{id:'rewards',name:'Recompensas',icon:'gift',views:['rewards']},{id:'events',name:'Mis planes',icon:'calendar',views:['events','calendar']}];nav.innerHTML=groups.map(g=>`<button type="button" class="nav-link ${g.views.includes(ui.view)?'active':''}" data-action="nav" data-view="${g.id}" ${g.views.includes(ui.view)?'aria-current="page"':''}>${icon(g.icon)}${g.name}</button>`).join('')+`<div class="nav-label">ESPACIO COMPARTIDO</div><button type="button" class="nav-link" data-action="nav" data-view="kitchen">${icon('tablet')}Vista tablet</button>`;}
  const mobile=$('.bottom-nav');if(mobile){const groups=isAdult()?GROUPS5:[{id:'member',name:'Tareas',icon:'tasks',views:['member','tasks','routines']},{id:'money',name:'Dinero',icon:'wallet',views:['money']},{id:'rewards',name:'Premios',icon:'gift',views:['rewards']},{id:'events',name:'Planes',icon:'calendar',views:['events','calendar']}];mobile.innerHTML=groups.map(g=>`<button type="button" class="${g.views.includes(ui.view)?'active':''}" data-action="nav" data-view="${g.id}" ${g.views.includes(ui.view)?'aria-current="page"':''}>${icon(g.icon)}<span>${g.name}</span></button>`).join('');}
  const main=$('#main-content');
  if(main){main.setAttribute('tabindex','-1');let views=isAdult()?group.views.filter(v=>v!=='member'):ui.view==='member'||ui.view==='tasks'||ui.view==='routines'?['member','tasks','routines']:ui.view==='calendar'||ui.view==='events'?['events','calendar']:[];
   if(views.length>1){const labels={home:'Resumen',inbox:'Revisiones',notifications:'Avisos',tasks:'Misiones',routines:'Rutinas',history:'Historial',calendar:'Calendario',events:'Eventos y listas',organize:'Convivencia',recipes:'Recetas y men\u00fa',shopping:'Compra',pantry:'Despensa',family:'Personas',money:'Paga y ahorro',rewards:'Recompensas',settings:'Ajustes',member:'Mi d\u00eda'};main.insertAdjacentHTML('afterbegin',`<nav class="section-nav" aria-label="Dentro de ${group.name}">${views.map(v=>`<button class="${ui.view===v?'active':''}" type="button" data-action="nav" data-view="${v}" ${ui.view===v?'aria-current="page"':''}>${esc(labels[v])}${v==='inbox'&&C.approvalItems(state).length?`<span class="pill">${C.approvalItems(state).length}</span>`:''}</button>`).join('')}</nav>`);}
   if(ui.view==='home'&&isAdult())enhanceHome5(main);
  }
  if(!isAdult())$('.sidebar-bottom [data-view=settings]')?.remove();
  if(isAdult()){const bar=$('.topbar>.flex');if(bar)bar.insertAdjacentHTML('afterbegin',`<button class="icon-btn notification-button" type="button" data-action="nav" data-view="inbox" aria-label="Revisiones pendientes: ${C.approvalItems(state).length}">${icon('check')}${C.approvalItems(state).length?`<span>${C.approvalItems(state).length}</span>`:''}</button>`);}
  let skip=document.querySelector('.skip-content');if(!skip){skip=document.createElement('a');skip.href='#main-content';skip.className='skip-content';skip.textContent='Saltar al contenido';document.body.prepend(skip);}
  if(!web5.initializedRoute){web5.initializedRoute=true;if(web5.initialHash.startsWith('#/')){try{history.replaceState({},'',web5.initialHash);}catch(_){}readRoute5();return;}}
  writeRoute5();
}
function nav(view){if(view==='meeting')view='home';if(!viewAllowed5(view))view='member';if(view==='member'&&!isAdult())ui.memberId=actor.memberId;if(view==='kitchen'){enterKitchen();return;}ui.view=view;render();window.scrollTo({top:0,behavior:'auto'});$('#main-content')?.focus({preventScroll:true});}
function modalSnapshot5(){const form=$('#modal-form');if(!form)return '';return JSON.stringify([...form.querySelectorAll('input,select,textarea')].map(e=>[e.name,e.type==='checkbox'||e.type==='radio'?e.checked:e.value]));}
function openModal(title,body,submit=null,ctx={}){web5.modalDirty=false;web5.modalInitial='';openModalBefore5(title,body,submit,ctx);queueMicrotask(()=>{web5.modalInitial=modalSnapshot5();});}
function closeModal(force=false){
 const d=$('#modal');if(!d?.open)return true;
 if(!force&&modalSubmit&&web5.modalInitial&&modalSnapshot5()!==web5.modalInitial){if(!d.querySelector('.discard-warning'))d.querySelector('.modal-header').insertAdjacentHTML('afterend',`<div class="discard-warning" role="alert"><p><b>Hay cambios sin guardar.</b> Puedes seguir editando o descartarlos.</p><div class="flex wrap">${btn('Seguir editando','web5-keep','','primary small')}${btn('Descartar cambios','web5-discard','','danger small')}</div></div>`);d.scrollTop=0;d.querySelector('[data-action=web5-keep]')?.focus();return false;}
 closeModalBefore5();web5.modalInitial='';web5.modalDirty=false;return true;
}
function enhanceHome5(main){
 const children=activeMembers().filter(m=>m.role==='member'),present=activeMembers().filter(m=>C.presenceOn(state,m.id,C.iso()).present);
 const note=`<div class="today-presence"><span class="eyebrow">HOY EN CASA</span><div class="flex wrap">${present.map(m=>`<span class="person-presence">${avatar(m,'small')}${esc(m.name)}</span>`).join('')||'<span>No hay convivencia prevista hoy.</span>'}</div></div>`;
 main.querySelector('.page-heading')?.insertAdjacentHTML('afterend',note);
 if(!state.demo&&!state.settings.onboardingDismissed){const steps=[{done:children.length>0,label:'Personas',view:'family'},{done:state.presencePlans.length>0,label:'Convivencia (opcional)',view:'organize'},{done:state.templates.length>0,label:'Tareas',view:'tasks'},{done:state.finance.accounts.length>0,label:'Paga (opcional)',view:'money'}];main.querySelector('.today-presence')?.insertAdjacentHTML('afterend',`<section class="setup-panel"><div class="flex between wrap"><h3>Dejad La Homa a vuestra medida</h3>${btn('Ocultar gu\u00eda','web5-setup-dismiss','','ghost small')}</div><div class="setup-steps">${steps.map((s,i)=>`<button type="button" data-action="nav" data-view="${s.view}"><span>${s.done?icon('check'):i+1}</span>${s.label}</button>`).join('')}</div><p class="small muted">Una cuenta es para un adulto. Los ni\u00f1os tienen perfiles, sin correo propio.</p></section>`);}
}
function renderInbox5(){if(!isAdult())return empty('Solo para adultos','Vuelve a tus tareas.');const list=C.approvalItems(state);return `${heading('Pendiente de vuestra revisi\u00f3n.', 'Tareas, gastos y planes. Todo lo que necesita un adulto.',btn('Ver avisos','nav','data-view="notifications"','secondary','calendar'))}<div class="panel">${list.map(x=>`<article class="review-row"><div class="grow"><span class="eyebrow">${esc({task:'TAREA REALIZADA',correction:'SOLICITUD DE RECTIFICACI\u00d3N',spend:'GASTO SOLICITADO',voucher:'RECOMPENSA'}[x.type])}</span><h3>${esc(x.title)}</h3><p>${esc(member(x.memberId).name)}${x.note?' \u00b7 '+esc(x.note):''}</p></div><div class="flex wrap">${btn('Revisar','web5-review',`data-id="${esc(x.id)}" data-type="${x.type}" data-week="${x.week||''}"`,'primary small','check')}</div></article>`).join('')||empty('Todo revisado.','Las nuevas solicitudes aparecer\u00e1n aqu\u00ed.')}</div><section class="settings-group mt"><h3>Actividad reciente</h3><p>Registro visible solo para el adulto de este dispositivo. La identificaci\u00f3n por cuenta real se activa con la nube.</p>${state.houseLog.slice(0,30).map(x=>`<div class="audit-row"><span>${esc(x.action)}</span><time>${esc(new Date(x.at).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}))}</time></div>`).join('')||'<p class="mt">Todav\u00eda no hay cambios registrados.</p>'}</section>`;}
function notificationSettings5(){if(!needAdult())return;const n=state.settings.notifications;openModal('Cu\u00e1ndo avisarnos',`<p class="dialog-description">La bandeja funciona en esta web. El env\u00edo con la web cerrada requiere activar el servicio de notificaciones al desplegar.</p>${['enabled','events','checklists','approvals','allowance'].map((k,i)=>`<label class="check-label"><input name="${k}" type="checkbox" ${n[k]?'checked':''}>${['Activar avisos','Planes pr\u00f3ximos','Preparativos pendientes','Revisiones del adulto','Paga por confirmar'][i]}</label>`).join('')}<div class="form-grid">${field('Antelaci\u00f3n de los eventos (minutos)','leadMinutes',n.leadMinutes,'number','min="0" max="10080" required')}${field('No molestar desde','quietStart',n.quietStart,'time','required')}${field('No molestar hasta','quietEnd',n.quietEnd,'time','required')}</div>${footer('Guardar preferencias')}`,fd=>transact(s=>{s.settings.notifications=Object.fromEntries(['enabled','events','checklists','approvals','allowance'].map(k=>[k,!!fd.get(k)]));Object.assign(s.settings.notifications,{leadMinutes:Number(fd.get('leadMinutes')),quietStart:fd.get('quietStart'),quietEnd:fd.get('quietEnd')});},'Preferencias guardadas.'));}
function renderNotifications5(){const items=C.reminderItems(state).filter(x=>isAdult()||x.kind!=='adult'&&(!x.memberIds.length||x.memberIds.includes(actor.memberId)));return `${heading('Para que no se nos pase.', 'Pr\u00f3ximos planes y preparativos pendientes.',isAdult()?btn('Configurar avisos','web5-notification-settings','','secondary','settings'):'')}<div class="note mb"><b>Avisos dentro de La Homa.</b> El env\u00edo en segundo plano no est\u00e1 activado en este archivo local. Tus horarios de silencio quedan guardados para el servicio web.</div><div class="panel">${items.map(x=>`<article class="review-row"><div class="grow"><h3>${esc(x.title)}</h3><p>${esc(x.detail)}</p></div>${btn('Abrir',x.eventId?'ev31-detail':'nav',x.eventId?`data-id="${esc(x.eventId)}"`:`data-view="${x.view}"`,'secondary small','arrow')}</article>`).join('')||empty('Nada urgente.','Los planes pr\u00f3ximos y los preparativos vencidos aparecer\u00e1n aqu\u00ed.')}</div>`;}
function renderTasksV2(){let html=renderTasksBefore5();if(isAdult())html=html.replace('</div></div>','</div></div>');return html+(isAdult()?`<div class="context-toolbar mt">${btn('Plantillas de tareas','web5-task-presets','','secondary','plus')}</div>`:'');}
function taskForm(id=null,mid=null){taskFormBefore5(id,mid);if(!isAdult())return;const t=state.templates.find(t=>t.id===id),freq=$('#modal [name=frequency]');if(!freq)return;freq.insertAdjacentHTML('beforeend','<option value="flexible">Cuota semanal: cualquier d\u00eda en casa</option><option value="monthly">Mensual: d\u00eda y siguiente estancia</option>');freq.value=t?.frequency||'daily';const grid=freq.closest('.form-grid');grid.insertAdjacentHTML('afterend',`<div class="form-grid mt" id="web5-task-options">${field('Veces por semana (cuota flexible)','quota',t?.quota||3,'number','min="1" max="7" required')}${field('D\u00eda del mes (mensual)','monthDay',t?.monthDay||1,'number','min="1" max="28" required')}</div><p class="small muted mt">Cuota flexible: hasta la cantidad indicada, m\u00e1ximo una vez por d\u00eda de estancia. Las tareas mensuales se mueven al siguiente d\u00eda en casa dentro del mes.</p><label class="check-label"><input name="allowEarly" type="checkbox" ${t?.allowEarly?'checked':''}>Permitir que se haga antes de su fecha</label>`);if(t)$('#modal .modal-footer').insertAdjacentHTML('afterbegin',btn('Duplicar','web5-task-duplicate',vattr(t.id),'secondary'));}
function eventForm(id=null,d=null,copyId=null,type='family'){
 eventFormBefore5(id,d,copyId,type);if(!isAdult())return;
 const e=state.events.find(e=>e.id===(id||copyId)),root=e?.seriesId?state.events.find(x=>x.id===e.seriesId):null,spec=root?.recurrence||e?.recurrence||{frequency:'none',interval:1,until:C.addDays(e?.date||d||C.iso(),90)};
 const insert=$('#modal .checklist-editor');
 insert?.insertAdjacentHTML('beforebegin',`<section class="recurrence-editor"><h3>Repetici\u00f3n y aviso</h3>${e?.seriesId&&!copyId?`<div class="note mb">Esta fecha pertenece a una serie. ${btn('Editar la serie','web5-series-edit',vattr(e.seriesId),'secondary small')}</div>`:''}<div class="form-grid">${selectField('Repetir','recurrenceFrequency',[{value:'none',label:'No se repite'},{value:'daily',label:'Cada d\u00eda'},{value:'weekly',label:'Cada semana'},{value:'monthly',label:'Cada mes'}],e?.seriesId&&e.id!==e.seriesId?'none':spec.frequency)}${field('Cada cu\u00e1ntos periodos','recurrenceInterval',spec.interval||1,'number','min="1" max="12" required')}${field('Repetir hasta (incluida)','recurrenceUntil',spec.until||C.addDays(e?.date||C.iso(),90),'date')}${field('Aviso previo (minutos)','reminderMinutes',e?.reminderMinutes??state.settings.notifications.leadMinutes,'number','min="0" max="10080" required')}</div>${e?.seriesId&&!copyId?selectField('Aplicar los cambios a','seriesScope',[{value:'single',label:'Solo esta fecha'},{value:'series',label:'Serie: futuras fechas sin excepciones'}],e.id===e.seriesId?'series':'single'):'<input type="hidden" name="seriesScope" value="series">'}<p class="small muted">La repetici\u00f3n semanal usa el d\u00eda de la fecha inicial. La mensual omite los meses que no tienen ese d\u00eda. Los avisos externos requieren activar el servicio web.</p></section>`);
}
function renderShoppingV2(){
 const lists=state.shoppingLists.filter(l=>!l.archived);if(!lists.some(l=>l.id===web5.shoppingList))web5.shoppingList='groceries';const all=state.shopping;let html;
 try{state.shopping=all.filter(x=>x.listId===web5.shoppingList);html=renderShoppingBefore5();}finally{state.shopping=all;}
 const list=lists.find(l=>l.id===web5.shoppingList),prefix=`<div class="list-toolbar"><label class="field"><span>Lista activa</span><select data-change="web5-list" aria-label="Lista activa">${selectOptions(lists.map(l=>({value:l.id,label:l.icon+' '+l.name})),web5.shoppingList)}</select></label>${isAdult()?btn('Nueva lista','web5-list-new','','secondary','plus'):''}${isAdult()&&list.id!=='groceries'?btn('Archivar','web5-list-archive',vattr(list.id),'ghost small'):''}${btn('Habituales','web5-usual','','secondary','history')}</div>`;
 return prefix+html;
}
function shoppingForm(id){shoppingFormBefore5(id);const x=state.shopping.find(x=>x.id===id);if(!$('#modal-form'))return;$('#modal .modal-footer').insertAdjacentHTML('beforebegin',selectField('Guardar en la lista','listId',state.shoppingLists.filter(l=>!l.archived).map(l=>({value:l.id,label:l.name})),x?.listId||web5.shoppingList));}
function renderMenu(){return `<div class="menu-tools">${btn('Copiar semana anterior','web5-menu-copy','','secondary','copy')}${btn('Guardar este men\u00fa','web5-menu-save','','secondary','heart')}${state.savedMenus.length?btn('Mis men\u00fas guardados','web5-menu-library','','secondary','book'):''}</div>`+renderMenuBefore5();}
function mealForm(d=null,slot=null,recipeId=null,servings=null){mealFormBefore5(d,slot,recipeId,servings);if(!isAdult())return;const dateInput=$('#modal [name=date]'),n=$('#modal [name=servings]');if(!dateInput||!n)return;const update=()=>{const count=C.menuServings(state,dateInput.value);n.value=Math.max(1,count);let note=$('#meal-presence-note');if(!note){note=document.createElement('p');note.id='meal-presence-note';note.className='note mt';n.closest('.field').insertAdjacentElement('afterend',note);}note.textContent=count?`${count} personas previstas en casa. Ajusta las raciones si hay invitados o alguien no come aqu\u00ed.`:'No hay nadie previsto en casa. Confirma las raciones si vais a cocinar para invitados.';};if(!servings)update();dateInput.addEventListener('change',update);}
function recipeForm(id){recipeFormBefore5(id);if(!isAdult())return;const r=state.recipes.find(x=>x.id===id);$('#modal .modal-footer')?.insertAdjacentHTML('beforebegin',`${field('Etiquetas (separadas por comas)','tags',(r?.tags||[]).join(', '),'text','maxlength="200" placeholder="Vegetariana, sin lactosa, r\u00e1pida..."')}${field('Origen de la receta (opcional)','sourceUrl',r?.sourceUrl||'','url','maxlength="1000"')}<p class="small muted">Las etiquetas son anotaciones familiares. No verifican al\u00e9rgenos ni sustituyen revisar ingredientes y envases.</p>`);}
function renderRecipes(){let all=state.recipes,html;try{if(web5.diet!=='all')state.recipes=all.filter(r=>(r.tags||[]).includes(web5.diet));html=renderRecipesBefore5();}finally{state.recipes=all;}if(ui.recipeTab==='recipes'){const tags=[...new Set(all.flatMap(r=>r.tags||[]))];html=`<div class="recipe-tools">${isAdult()?btn('Importar receta','web5-recipe-import','','secondary','download'):''}<label class="field"><span>Etiqueta</span><select data-change="web5-diet">${selectOptions([{value:'all',label:'Todas las etiquetas'},...tags],web5.diet)}</select></label></div>`+html;}return html;}
function recipeImport5(){if(!needAdult())return;openModal('Importar una receta para revisarla',`${field('Enlace de la receta','url','','url','maxlength="1000" placeholder="https://..."')}<div class="mt">${btn('Leer el enlace','web5-recipe-fetch','','secondary','download')}</div><label class="field mt"><span>O pega el HTML / JSON-LD de una receta</span><textarea name="source" maxlength="1000000" rows="6" placeholder="Contenido con datos estructurados de tipo Recipe"></textarea></label><div class="note">Se extraen los datos estructurados de la p\u00e1gina, sin ejecutar sus scripts. Siempre se abre un borrador para revisar cantidades, ingredientes y pasos antes de guardar. Leer un enlace externo requiere la conexi\u00f3n web del servidor; el pegado funciona sin ella.</div>${footer('Preparar borrador')}`,fd=>{const recipe=window.HomaRecipeImport.parse(String(fd.get('source')),String(fd.get('url')));closeModal(true);openImportedRecipe5(recipe);return false;});}
function openImportedRecipe5(r){recipeForm();const form=$('#modal-form');for(const k of ['name','servings','minutes','emoji','sourceUrl'])if(form.elements[k])form.elements[k].value=r[k]||({servings:4,minutes:30,emoji:'\u{1F37D}\uFE0F'}[k])||'';form.elements.steps.value=r.steps.join('\n');$('#ingredients-editor').innerHTML=r.ingredients.map(ingredientEditor).join('');web5.modalInitial='imported';toast('Borrador importado. Revisa las cantidades antes de guardar.');}
function fileSection5(e){const files=state.eventFiles.filter(f=>f.eventId===e.id);return `<section class="settings-group mt"><div class="flex between wrap"><div><h3>Documentos del evento</h3><p>Solo adultos. Se guardan en este navegador hasta activar la nube.</p></div>${btn('Adjuntar','web5-file-add',vattr(e.id),'secondary','plus')}</div>${files.map(f=>`<div class="settings-row"><div class="grow"><h4>${esc(f.name)}</h4><p>${Math.ceil(f.size/1024)} KB${f.expires?' \u00b7 Revisar para eliminar el '+esc(f.expires):''}</p></div>${btn('Abrir','web5-file-open',vattr(f.id),'secondary small')}${iconBtn('trash','web5-file-delete','Eliminar documento',vattr(f.id))}</div>`).join('')}</section>`;}
function eventDetail31(id){eventDetailBefore5(id);const e=state.events.find(x=>x.id===id);if(e&&isAdult())$('#modal .modal-body')?.insertAdjacentHTML('beforeend',fileSection5(e));}
function taskPresets5(){if(!needAdult())return;const sets=[['Hacer la cama','bed','daily',2],['Recoger los juguetes','blocks','daily',3],['Poner la mesa','utensils','daily',3],['Regar las plantas','plant','flexible',4],['Ordenar la habitaci\u00f3n','house','weekly',5],['Preparar la mochila','book','daily',3]];openModal('Una base para empezar',`<p class="dialog-description">Elige una tarea y adapta sus responsables, puntos y frecuencia. Ninguna se asigna por edad de forma autom\u00e1tica.</p>${sets.map((s,i)=>`<button type="button" class="profile-option" data-action="web5-task-preset" data-index="${i}">${icon(s[1])}<div><b>${esc(s[0])}</b><p>${s[2]==='flexible'?'Cuota semanal':s[2]==='weekly'?'Una vez por semana':'Diaria'}</p></div></button>`).join('')}`,null,{presets:sets});}
function renderSettingsV2(){return renderSettingsBefore5()+`<section class="settings-group"><h3>Zona horaria y avisos</h3><p>La familia usa <b>${esc(state.settings.timeZone)}</b>. La versi\u00f3n en nube validar\u00e1 puntos y dinero con el reloj del servidor.</p><div class="flex wrap mt">${btn('Zona horaria','web5-timezone','','secondary','calendar')}${btn('Avisos','web5-notification-settings','','secondary','settings')}${btn('Conexiones y estado','web5-connections','','secondary','link')}</div></section>`;}
function enhanceAuth5(){if(access.target==='cloud'&&!document.querySelector('.cloud-stage-note'))document.querySelector('.auth-card')?.insertAdjacentHTML('beforeend','<p class="note warning cloud-stage-note">La conexi&oacute;n de hogares de la web est&aacute; en preparaci&oacute;n. El registro local y la demostraci&oacute;n funcionan; este archivo no activa la sincronizaci&oacute;n entre dispositivos.</p>');const f=$('#access-form');if(f&&access.tab==='login'&&!$('.auth-recovery'))f.insertAdjacentHTML('afterend',`<button type="button" class="text-btn auth-recovery" data-action="web5-forgot">He olvidado mi contrase\u00f1a</button>`);}
function resetPassword5(){if(access.target!=='cloud'){openModal('Recuperaci\u00f3n de cuenta local','<p class="dialog-description">Una cuenta local no env\u00eda correos de recuperaci\u00f3n. Conserva una copia privada de tu familia. En una cuenta web, podr\u00e1s recuperar el acceso con tu correo verificado.</p>'+btn('Entendido','close','','primary'));return;}openModal('Recuperar el acceso',`${field('Tu correo','email','','email','required maxlength="254" autocomplete="email"')}${footer('Enviar enlace')}`,async fd=>{const client=await cloudClient();const {error}=await client.auth.resetPasswordForEmail(fd.get('email'),{redirectTo:location.origin+location.pathname+'?recovery=1'});if(error)throw error;toast('Si existe una cuenta, recibir\u00e1s un enlace para restablecerla.');return true;});}
async function web5Action(a,d,el,event){
 switch(a){
 case 'event-delete':{if(!needAdult())return true;const ev=state.events.find(x=>x.id===d.id);openModal('Eliminar evento',`<p class="dialog-description">Se eliminan el evento y su checklist; no se modifica la convivencia ni una copia ya exportada.</p>${ev?.seriesId?selectField('Alcance','scope',[{value:'single',label:'Solo esta fecha'},{value:'series',label:'Todas las fechas futuras de la serie'}],'single'):'<input name="scope" type="hidden" value="single">'}${footer('Eliminar')}`,fd=>transact(st=>C.deleteEventSeries(st,d.id,fd.get('scope'),actor),'Evento eliminado.'));return true;}
 case 'web5-keep':web5.queued=null;$('.discard-warning')?.remove();return true;
 case 'web5-discard':closeModal(true);if(web5.queued){const fn=web5.queued;web5.queued=null;fn();}return true;
 case 'nav':if($('#modal').open&&!closeModal()){web5.queued=()=>nav(d.view);return true;}return false;
 case 'web5-review':{
  const x=C.approvalItems(state).find(x=>x.id===d.id&&x.type===d.type);if(!x)return true;
  if(x.type==='task'){taskStateModal(x.week,x.id);return true;}
  if(x.type==='correction'){openModal('Revisar rectificaci\u00f3n',`<p class="dialog-description"><b>${esc(x.title)}</b><br>${esc(member(x.memberId).name)}${x.note?'<br>'+esc(x.note):''}</p><div class="note">La puntuaci\u00f3n no ha cambiado al solicitar la revisi\u00f3n.</div><div class="modal-footer">${btn('Rechazar','web5-review-resolve',`data-id="${x.id}" data-approve="no"`,'secondary')}${btn('Aprobar rectificaci\u00f3n','web5-review-resolve',`data-id="${x.id}" data-approve="yes"`,'primary')}</div>`);return true;}
  if(x.type==='spend'){ui.moneyMember=x.memberId;nav('money');return true;}if(x.type==='voucher'){ui.rewardTab='vouchers';nav('rewards');return true;}return true;
 }
 case 'web5-task-review':{openModal('Pedir una revisi\u00f3n',`<p class="dialog-description">Un adulto revisar\u00e1 lo ocurrido. Tus puntos no cambian hasta que lo confirme.</p><label class="field"><span>Qu\u00e9 quieres explicar (opcional)</span><textarea name="note" maxlength="500"></textarea></label>${footer('Enviar solicitud')}`,fd=>transact(s=>C.requestTaskReview(s,d.week,d.id,actor,fd.get('note')),'Solicitud enviada.'));return true;}
 case 'web5-review-resolve':if(transact(s=>C.resolveTaskReview(s,d.id,d.approve==='yes',actor),'Revisi\u00f3n resuelta.'))closeModal(true);return true;
 case 'web5-setup-dismiss':transact(s=>s.settings.onboardingDismissed=true);return true;
 case 'web5-notification-settings':notificationSettings5();return true;
 case 'web5-task-presets':taskPresets5();return true;
 case 'web5-task-preset':{const s=modalContext.presets[Number(d.index)];closeModal(true);taskForm();const f=$('#modal-form');f.elements.title.value=s[0];f.elements.icon.value=[...f.elements.icon.options].some(o=>o.value===s[1])?s[1]:'house';f.elements.frequency.value=s[2];f.elements.points.value=s[3];return true;}
 case 'web5-task-duplicate':{const t=state.templates.find(x=>x.id===d.id);if(!t)return true;closeModal(true);taskForm();const f=$('#modal-form');for(const k of ['title','description','points','frequency','category','icon','quota','monthDay'])if(f.elements[k]&&t[k]!=null)f.elements[k].value=k==='title'?'Copia de '+t[k]:t[k];f.querySelectorAll('[name=members]').forEach(x=>x.checked=t.memberIds.includes(x.value));return true;}
 case 'web5-series-edit':{if(!closeModal()){web5.queued=()=>eventForm(d.id);return true;}eventForm(d.id);return true;}
 case 'web5-list-new':openModal('Nueva lista',`${field('Nombre','name','','text','required maxlength="60" placeholder="Farmacia, colegio, supermercado..."')}${field('Icono','icon','\u{1F6D2}','text','required maxlength="20"')}${footer('Crear lista')}`,fd=>transact(s=>{web5.shoppingList=C.addShoppingList(s,fd.get('name'),actor,fd.get('icon')).id;},'Lista creada.'));return true;
 case 'web5-list-archive':confirmDialog('Archivar lista','La lista se oculta. Sus productos comprados se conservan.',()=>transact(s=>C.archiveShoppingList(s,d.id,actor),'Lista archivada.'));return true;
 case 'web5-usual':{const items=[...new Map(state.usualProducts.slice().reverse().map(x=>[C.foodKey(x.name),x])).values()].slice(0,30);openModal('Volver a comprar',items.map(x=>`<button type="button" class="profile-option" data-action="web5-usual-add" data-id="${x.id}">${foodMedia(x)}<span>${esc(x.name)}<small class="muted"> \u00b7 ${esc(x.quantity)}</small></span></button>`).join('')||empty('Todav\u00eda no hay productos habituales.','Aparecer\u00e1n los que vay\u00e1is marcando como comprados.'));return true;}
 case 'web5-usual-add':{transact(s=>{const x=s.usualProducts.find(x=>x.id===d.id);if(!x)throw new Error('Producto no disponible.');if(s.shopping.some(y=>!y.checked&&y.listId===web5.shoppingList&&C.foodKey(y.name)===C.foodKey(x.name)))throw new Error('Ya est\u00e1 pendiente en esta lista.');s.shopping.push({...x,id:C.uid('shop'),checked:false,listId:web5.shoppingList});},'A\u00f1adido a la lista activa.');closeModal(true);return true;}
 case 'shopping-clear':confirmDialog('Limpiar esta lista','Se retiran los productos comprados de esta lista. Las otras listas no cambian.',()=>transact(s=>{s.shopping=s.shopping.filter(x=>x.listId!==web5.shoppingList||!x.checked);},'Lista despejada.'));return true;
 case 'shopping-copy':{const text=state.shoppingLists.find(l=>l.id===web5.shoppingList)?.name+'\n\n'+state.shopping.filter(x=>x.listId===web5.shoppingList&&!x.checked).map(x=>'[ ] '+x.name+' - '+x.quantity).join('\n');try{await navigator.clipboard.writeText(text);toast('Lista copiada.');}catch(_){downloadFile('la-homa-lista.txt',text);}return true;}
 case 'web5-menu-copy':openModal('Reutilizar el men\u00fa anterior',`<p class="dialog-description">Se copiar\u00e1n los platos de la semana anterior en los huecos libres. No se borra lo que ya has planificado.</p><label class="check-label"><input type="checkbox" name="adjust" checked>Ajustar raciones seg\u00fan convivencia</label>${footer('Copiar y revisar')}`,fd=>{let r;const ok=transact(s=>{r=C.copyMenu(s,C.addDays(ui.menuStart,-7),ui.menuStart,actor,!!fd.get('adjust'));});if(ok)toast(`${r.copied} platos copiados; ${r.skipped} huecos ya ocupados o sin convivencia.`);return ok;});return true;
 case 'web5-menu-save':openModal('Guardar un men\u00fa habitual',`${field('Nombre','name','','text','required maxlength="80" placeholder="Semana f\u00e1cil, men\u00fa de invierno..."')}${footer('Guardar men\u00fa')}`,fd=>transact(s=>C.saveMenu(s,ui.menuStart,fd.get('name'),actor),'Men\u00fa guardado.'));return true;
 case 'web5-menu-library':openModal('Vuestros men\u00fas',state.savedMenus.map(m=>`<button type="button" class="profile-option" data-action="web5-menu-apply" data-id="${m.id}"><b>${esc(m.name)}</b><span>${m.plans.length} platos</span></button>`).join('')+'<div class="note mt">Se completar\u00e1n solo los huecos libres de la semana visible. Las raciones se adaptar\u00e1n a la convivencia.</div>');return true;
 case 'web5-menu-apply':if(transact(s=>C.applySavedMenu(s,d.id,ui.menuStart,actor),'Men\u00fa aplicado.'))closeModal(true);return true;
 case 'web5-recipe-import':recipeImport5();return true;
 case 'web5-recipe-fetch':{const url=$('#modal [name=url]').value;if(!cloudConfigured())throw new Error('La lectura de enlaces se activa al conectar el servidor. Puedes usar el campo de contenido para probar el importador.');el.disabled=true;try{const result=await cloudFunction5('recipe-import',{url});$('#modal [name=source]').value=JSON.stringify(result.recipe);}finally{el.disabled=false;}return true;}
 case 'web5-file-add':{
  if(!needAdult())return true;openModal('Adjuntar un documento',`<input type="hidden" name="eventId" value="${esc(d.id)}"><label class="field"><span>PDF, imagen o texto. M\u00e1ximo 5 MB.</span><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt" required></label>${field('Fecha para revisar su eliminación (opcional)','expires','','date')}${footer('Guardar documento')}`,async fd=>{const file=fd.get('file');if(!file?.size||file.size>5*1024*1024)throw new Error('Elige un archivo de hasta 5 MB.');if(!['application/pdf','image/jpeg','image/png','image/webp','text/plain'].includes(file.type))throw new Error('Formato no permitido.');const id=C.uid('asset');await window.HomaAssets.put(KEY,id,file);const ok=transact(s=>s.eventFiles.push({id,eventId:d.id,name:file.name.slice(0,200),mime:file.type,size:file.size,expires:fd.get('expires')||'',createdAt:new Date().toISOString()}),'Documento guardado.');if(!ok)await window.HomaAssets.remove(KEY,id);return ok;});return true;
 }
 case 'web5-file-open':{if(!needAdult())return true;const f=state.eventFiles.find(f=>f.id===d.id);const blob=await window.HomaAssets.get(KEY,d.id);if(!blob)throw new Error('El archivo no est\u00e1 en este dispositivo. Restaura una copia completa.');const url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download=f.name;ael.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return true;}
 case 'web5-file-delete':{if(!needAdult())return true;confirmDialog('Eliminar documento','Se eliminar\u00e1 el documento de este evento.',async()=>{const ok=transact(s=>s.eventFiles=s.eventFiles.filter(f=>f.id!==d.id));if(ok)await window.HomaAssets.remove(KEY,d.id);return ok;},'Eliminar');return true;}
 case 'backup-export':{if(!needAdult())return true;const bundle=await window.HomaAssets.exportBundle(KEY,state.eventFiles.map(f=>f.id));downloadFile('la-homa-copia-completa-'+C.iso()+'.json',JSON.stringify({...state,assetBundle:bundle},null,2),'application/json');toast('Copia completa creada, incluidos los adjuntos disponibles.');return true;}
 case 'web5-forgot':resetPassword5();return true;
 case 'web5-timezone':openModal('Zona horaria del hogar',`${field('Zona horaria IANA','zone',state.settings.timeZone,'text','required maxlength="80" placeholder="Europe/Madrid"')}<p class="note">Se guarda una sola zona para el hogar. El servidor la usar\u00e1 al activar la nube. Este prototipo a\u00fan usa el reloj del dispositivo para las operaciones locales.</p>${footer('Guardar')}`,fd=>transact(s=>{new Intl.DateTimeFormat('es',{timeZone:fd.get('zone')});s.settings.timeZone=fd.get('zone');},'Zona horaria guardada.'));return true;
 case 'web5-connections':openModal('Conexiones de la web',`<div class="connection-row"><b>Datos locales</b><span>Activos en este navegador</span></div><div class="connection-row"><b>Cuenta y base de datos web</b><span>${cloudConfigured()?'Configuraci\u00f3n introducida; requiere comprobar el despliegue':'Pendiente de conectar Supabase'}</span></div><div class="connection-row"><b>Google Calendar</b><span>Pendiente de autorizar una conexi\u00f3n de calendario; iniciar sesi\u00f3n con Google no la activa</span></div><div class="connection-row"><b>Apple Calendar</b><span>Intercambio ICS; suscripci\u00f3n privada prevista en servidor</span></div><div class="connection-row"><b>Avisos con la web cerrada</b><span>Pendiente de servicio de env\u00edo y permisos</span></div><p class="note mt">El proyecto incluye la gu\u00eda de despliegue y el estado real de cada integraci\u00f3n. No se muestran conexiones simuladas.</p><div class="modal-footer">${btn('Entendido','close','','primary')}</div>`);return true;
 }
 return false;
}
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.change==='web5-list'){web5.shoppingList=el.value;render();}if(el.dataset.change==='web5-diet'){web5.diet=el.value;render();}});
window.addEventListener('beforeunload',e=>{if($('#modal')?.open&&modalSubmit&&web5.modalInitial&&modalSnapshot5()!==web5.modalInitial){e.preventDefault();e.returnValue='';}});
$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});

document.addEventListener('change',e=>{if(e.target.dataset.change==='task-frequency'&&['flexible','monthly'].includes(e.target.value)){document.querySelectorAll('#modal [name=days]').forEach(x=>x.checked=true);const hint=document.querySelector('#frequency-hint');if(hint)hint.textContent=e.target.value==='flexible'?'Hasta la cuota elegida, en días distintos en casa. Se limita a tus días disponibles.':'Una vez al mes, desde el día elegido, en el primer día de convivencia.';}});

async function cloudFunction5(name,payload){const client=await cloudClient();const {data,error}=await client.functions.invoke(name,{body:payload});if(error)throw new Error('El servicio web no ha podido completar la solicitud. Revisa su despliegue y permisos.');return data;}
